### ISSUE TITLE
Cannot build with MSVC 2019 Version 16.3.0 Preview 2.0

### ISSUE THREAD

**Issue by jonathansharman** [ericniebler/range-v3#1265] opened 2019-08-20 06:17 UTC
After updating from Preview 1.0 to Preview 2.0, the following fails to compile:

    #include <range/v3/all.hpp>
    int main() {
        return 0;
    }

Errors:

    'meta::detail::lambda_': template parameter 'Tags' is incompatible with the declaration 'meta::detail::lambda_<meta::list<Ts...>,true>'
    'Bs': template parameter not used or deducible in partial specialization 'meta::detail::lambda_<meta::list<Ts...>,true>::impl<meta::detail::lambda_<meta::list<Ts...>,true>,Args>'	
    'IsVar': template parameter not used or deducible in partial specialization 'meta::detail::lambda_<meta::list<Ts...>,true>::impl<meta::detail::lambda_<meta::list<Ts...>,true>,Args>'	
    'meta::detail::lambda_': use of class template requires template argument list

I don't know if this is a regression in MSVC or if  exposes a bug in range-v3.

**Comment by CaseyCarter** [comment] 2019-08-22 00:13
Is this with `/std:c++latest`? Actually, could you provide a full command line and the output from CL /Bc?

**Comment by jonathansharman** [comment] 2019-08-22 02:52
Full commandline options:

    /experimental:module /permissive- /GS /GL /analyze- /W4 /wd"5105" /Gy /Zc:wchar_t /Zi /Gm- /O2 /Fd"Release\vc142.pdb" /Zc:inline /fp:precise /D "WIN32" /D "NDEBUG" /D "_CONSOLE" /D "_UNICODE" /D "UNICODE" /errorReport:prompt /WX /Zc:forScope /Gd /Oy- /Oi /MD /std:c++latest /FC /Fa"Release\" /EHsc /nologo /Fo"Release\" /Fp"Release\test.pch" /diagnostics:column /permissive- /experimental:preprocessor 

`cl /Bv` output:

    Microsoft (R) C/C++ Optimizing Compiler Version 19.23.28008 for x86
    Copyright (C) Microsoft Corporation.  All rights reserved.

    Compiler Passes:
     C:\Program Files (x86)\Microsoft Visual 
    Studio\2019\Preview\VC\Tools\MSVC\14.23.28008\bin\HostX86\x86\cl.exe:        Version 19.23.28008.0
     C:\Program Files (x86)\Microsoft Visual 
    Studio\2019\Preview\VC\Tools\MSVC\14.23.28008\bin\HostX86\x86\c1.dll:        Version 19.23.28008.0
     C:\Program Files (x86)\Microsoft Visual 
    Studio\2019\Preview\VC\Tools\MSVC\14.23.28008\bin\HostX86\x86\c1xx.dll:      Version 19.23.28008.0
     C:\Program Files (x86)\Microsoft Visual 
    Studio\2019\Preview\VC\Tools\MSVC\14.23.28008\bin\HostX86\x86\c2.dll:        Version 19.23.28008.0
     C:\Program Files (x86)\Microsoft Visual 
    Studio\2019\Preview\VC\Tools\MSVC\14.23.28008\bin\HostX86\x86\link.exe:      Version 14.23.28008.0
     C:\Program Files (x86)\Microsoft Visual 
    Studio\2019\Preview\VC\Tools\MSVC\14.23.28008\bin\HostX86\x86\mspdb140.dll:  Version 14.23.28008.0
     C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.23.28008\bin\HostX86\x86\1033\clui.dll: Version 19.23.28008.0

    cl : Command line error D8003 : missing source filename

**Comment by CaseyCarter** [comment] 2019-08-22 15:57
(Putting on MSVC hat) I immediately suspect the combination of concepts and pre-compiled headers given that I've never done that, and I don't recall any compiler tests that combine concepts and PCH. I'll keep trying to repro this when I can get time, but you might want to try disabling pre-compiled headers to see if you get one of the errors fixed by #1263 (which makes all tests pass in 16.3p2 for me with `/std:c++latest`) instead.

**Comment by CaseyCarter** [comment] 2019-08-22 20:46
>  I immediately suspect the combination of concepts and pre-compiled headers

This doesn't seem to be the case. (The MSVC concepts implementer has also told me that he often builds range-v3 with pre-compiled headers, so that's not the likely cause.)

Luckily, [you indicated in your Developer Community bug](https://developercommunity.visualstudio.com/content/problem/700497/cannot-compile-range-v3-in-msvc-2019-version-1630.html) that you're using the vcpkg version of range-v3, which is the bit of info I was missing to reproduce the problem. I haven't updated range-v3 in vcpkg since 0.5.0 to avoid some of the churn on trunk, and 16.3p2's support for concepts is stumbling across old concepts bugs in meta.hpp.

Time to update.

**Comment by CaseyCarter** [comment] 2019-08-22 22:46
Since the above was not at all clear: the failure you're seeing is from a bug in range-v3 0.5.0 (which vcpkg installs) that was fixed long ago on trunk. Trunk is fairly stable right now, you could use it directly or wait for me to update vcpkg after #1275 is merged, at which time I'll close this issue.

**Comment by CaseyCarter** [comment] 2019-08-23 17:11
Vcpkg has been updated to a near-tip-of-trunk commit that should work with VS 2019 16.3p2 (i.e., "it works on my machine"). AFAIK this issue is solved.

**Closed by CaseyCarter** 2019-08-23 17:11 UTC
