### ISSUE TITLE
Compiled-time views?

### ISSUE THREAD

**Issue by krzysztof-jusiak** [ericniebler/range-v3#339] opened 2016-04-27 10:55 UTC
I was wondering whether compiled-time view were/are/will considered for range-v3 library?
Currently, it doesn't work, unless there is a specific syntax/magic to enable it?

```cpp
  assert(ranges::equal({0, 1}, ranges::view::ints | ranges::view::take(2)));
  static_assert(ranges::equal({0, 1}, ranges::view::ints | ranges::view::take(2)));
```

Such approach is possible with Boost.Hana, however, Hana purpose is different, so it doesn't have all goodies ranges have.

Motivation...
Simple board (known size) and col / row view could be calculated at compile time (which elements should be taken, not values) and verified during run-time with given values.

**Comment by gnzlbg** [comment] 2016-04-27 12:25
There was a PR for this a while ago that supported `view::ints` but the changes were both large and brittle (`constexpr` turned out to have some unexpected corner cases). 

The plan back then was to get constexpr algorithms (https://github.com/ericniebler/range-v3/pull/143) working first, and then move to `view` but I ran out of time. 

If anybody wants to work on this that PR should be easily updateable to the current master branch. If the 3 algorithms that can't be made `constexpr` without changing their API are left out it shouldn't be very hard to merge the rest. IIRC constexpr tests for all the algorithms are provided in that PR.

**Comment by krzysztof-jusiak** [comment] 2016-04-27 13:03
Thanks @gnzlbg, nice work on these PRs.

It would be absolutely awesome to have compile-time views and algorithms but yea, it's neither an easy nor a small task :/

**Comment by gnzlbg** [comment] 2016-04-27 14:45
Compile-time algorithms are actually pretty straight forward. Just stamp
constexpr in front of them and 90% of them just work, the random algorithms
were a bit more tricky and the rest cannot be made constexpr because they
allocate memory internally.  Testing the algorithms at compile-time was by
fare the most tedious part.

Views were not that hard either. They were more cumbersome because they use
a lot of utilities which need to be made constexpr. Some of them are part
of the `std::` and are not constexpr which is unfortunate. Some of these
can be easily worked around but for others like `std::swap` I don't recall
any good solutions since it is a customization point.

And well there were also lots of problems with constexpr functions being
always evaluated in non-evaluated contexts which used to break a lot of
things that were not properly constrained. The work by Casey and Eric on
the STL2 might have made this situation better in range-v3 but last time I
tried was almost 2 years ago.

**Comment by CaseyCarter** [comment] 2016-04-28 14:27
> And well there were also lots of problems with `constexpr` functions being always evaluated in non-evaluated contexts which used to break a lot of things that were not properly constrained.

This issue, sort of documented [on Standard - Discussion](https://groups.google.com/a/isocpp.org/forum/#!topic/std-discussion/6udLpHDvShU) [and in this LLVM bug report](http://reviews.llvm.org/D13386), was a killer for `constexpr` range-v3. There's discussion of the range-v3 impact [starting here in #125 (gnzlbg's thread on `constexpr`-ification)](https://github.com/ericniebler/range-v3/issues/125#issuecomment-94190225). Actually, this issue seems to be an exact duplicate of #125.

**Comment by rhalbersma** [comment] 2016-04-28 19:32
Also consider contacting @apolukhin regarding LEWG feedback on the `constexpr`-algorithms proposal [p0202r0](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0202r0.html) during Jacksonville.

**Comment by gnzlbg** [comment] 2016-04-28 19:42
I contacted him to expresses my support  but also my concerns on the
algorithms that  allocate memory as well as some implementations that use
goto internally (although that's a minor issue). Another issue is that
making a function constexpr might be an API breaking change due to the
issue that Casey mentions (so if this is desired it should be done for stl2
or stl3).

**Comment by ericniebler** [comment] 2016-05-04 21:55
Dupe of #125

**Closed by ericniebler** 2016-05-04 21:55 UTC
