### ISSUE TITLE
It seems that something is wrong with sort implementation

### ISSUE THREAD

**Issue by dieram3** [ericniebler/range-v3#140] opened 2015-05-01 09:23 UTC
Hi, I was playing with the library range-v3. I did benchmarking on sort, stable_sort and nth_element. Everything compares well respect to libc++ version except ranges::sort. It sorts well, but for some reason it becomes incredibly slow with large ranges (it can delay more than a minute to sort an array of 10M). Maybe a little bug?

**PD:** I compiled this in Release Mode.

Here is my code:
```C++
#include <iostream>
#include <vector>
#include <random>
#include <functional>
#include <climits>
#include <manu343726/range/v3/algorithm.hpp>

int main() {
  std::default_random_engine gen;
  std::uniform_int_distribution<> dist(INT_MIN, INT_MAX);
  std::vector<int> vec(10000000);
  ranges::generate(vec, std::bind(dist, std::ref(gen)));

  using namespace std::chrono;
  auto begin = steady_clock::now();
  ranges::sort(vec.begin(), vec.end());
  auto end = steady_clock::now();
  auto elapsed = duration_cast<milliseconds>(end - begin);
  std::cout << "Time: " << elapsed.count() << " ms\n";
}
```

**Comment by gnzlbg** [comment] 2015-05-01 13:19
I don't think `sort` has been optimized yet, but the complexity looks quadratic: 

```shell
#                N []      std::sort [ms]   ranges::sort [ms]
                   1                   0                   0
                   2                   0                   0
                   4                   0                   0
                   8                   0                   0
                  16                   0                   0
                  32                   0                   0
                  64                   0                   0
                 128                   0                   0
                 256                   0                   0
                 512                   0                   0
                1024                   0                   0
                2048                   0                   0
                4096                   0                   0
                8192                   0                   1
               16384                   1                   2
               32768                   1                  39
               65536                   4                  17
              131072                   8                 117
              262144                  20                 200
              524288                  41                2085
             1048576                  89               10509
             2097152                 193               36916
             4194304                 393              114919
```

**Comment by ericniebler** [comment] 2015-05-01 15:11
Interesting. The `sort` implementation comes from the old HP/SGI STL implementation. It's possible that back. I'm somewhat surprised to learn it's quadratic. Maybe I flubbed something when porting it to modern C++ with move semantics.

**Comment by dieram3** [comment] 2015-05-01 16:25
I found the bug :)

In this function:

```C++
template <typename I, typename Val, typename C, typename P>
inline I unguarded_partition(I begin, I end, Val const pivot, C &pred,
                             P &proj) {
  while (true) {
    while (pred(proj(*begin), pivot)) ++begin;
    --end;
    while (pred(pivot, proj(*end))) --end;
    if (!(begin < end)) return begin;
    ranges::iter_swap(begin, end);
    ++begin;
  }
}
```
I removed the reference from pivot since pivot is an element inside the range to be partitioned. It was constantly changing the pivot value. I suggest move the pivot to the end, then do the partition.

Further I found something curious.

In this function:

```C++
template <typename I, typename Size, typename C, typename P>
  static void introsort_loop(I begin, I end, Size depth_limit, C &pred,
                             P &proj) {
    while (end - begin > sort_fn::introsort_threshold()) {
      if (depth_limit == 0)
        return partial_sort(begin, end, end, std::ref(pred), std::ref(proj)),
               void();
      I cut = detail::unguarded_partition(
          begin, end,
          detail::median(proj(*begin), proj(*(begin + (end - begin) / 2)),
                         proj(*(end - 1)), pred),
          pred, proj);
      sort_fn::introsort_loop(cut, end, depth_limit - 1, pred, proj);
      end = cut;
    }
  }
```

Should not be:
```C++
sort_fn::introsort_loop(cut, end, --depth_limit, pred, proj);
```
Instead of:
```C++
sort_fn::introsort_loop(cut, end, depth_limit - 1, pred, proj);
```

**Comment by ericniebler** [comment] 2015-05-01 18:16
> I removed the reference from pivot since pivot is an element inside the range to be partitioned. It was constantly changing the pivot value. I suggest move the pivot to the end, then do the partition.

Hrm, yes that looks like a bug that I introduced while trying to support move-only types. I don't have time to play with this right now. Patches welcome.

> Should not be:
> ~~~~cpp
> sort_fn::introsort_loop(cut, end, --depth_limit, pred, proj);
> ~~~~
> Instead of:
> ~~~~cpp
> sort_fn::introsort_loop(cut, end, depth_limit - 1, pred, proj);
> ~~~~

Why would that make a difference?

**Comment by ericniebler** [comment] 2015-05-01 18:40
OK, I have a cheesy fix in the `sort-of-fix-sort` branch (09cc4c8). Can one of you see if it resolves the quadratic behavior?

It's cheesy because it adds two conditionals in `unguarded_partition`'s inner loop. It's the best I can do given my time constraints. If one of you has a better patch, I'll be grateful.

**Comment by ericniebler** [comment] 2015-05-01 19:05
UPDATE: I can confirm that at least on the example @dieram3 posted, this fix eliminates the bug. Will wait a while to see if you guys come up with something better.

**Comment by gnzlbg** [comment] 2015-05-01 19:12
@ericniebler I have no time for a fix right now but I threw out some benchmarking code (here: https://github.com/gnzlbg/range-v3/tree/sort_test ) that might be useful.

**Comment by dieram3** [comment] 2015-05-01 21:04
> >Should not be:
>>```C++
>> sort_fn::introsort_loop(cut, end, --depth_limit, pred, proj);
>>```
>> Instead of:
>>```C++
>> sort_fn::introsort_loop(cut, end, depth_limit - 1, pred, proj);
>>```

> Why would that make a difference?

What if in each iteration the *cut* becomes *end - 1*? 
This will trigger a quadratic behavior.

**Comment by ericniebler** [comment] 2015-05-01 21:10
> What if in each iteration cut becomes end - 1?

IIUC, that would only happen if every element in the sequence is less than the pivot. That seems pretty unlikely, especially since the pivot is the median of the first, last and middle values.

Besides, I fail to see how your insignificant change to the depth_limit would have any effect at all. Why should mutating depth_limit in place rather than subtracting one change anything?

**Comment by ericniebler** [comment] 2015-05-01 21:12
FYI, I merged my silly fix to master -- it's better than nothing -- and the numbers for @gnzlbg's benchmark look good to me.

**Comment by dieram3** [comment] 2015-05-01 21:24
> IIUC, that would only happen if every element in the sequence is less than the pivot. That seems pretty > unlikely, especially since the pivot is the median of the first, last and middle values.
> 
> Besides, I fail to see how your insignificant change to the depth_limit would have any effect at all. Why > should mutating depth_limit in place rather than subtracting one change anything?

Hmm, for consistency.

It is supposed to guarantee a n*log(n) complexity. This is done thanks to the depth limit variable. But it is used only by the right side of each partition.

The left partition (that is not worked recursively), each time becomes smaller, but ignores totally the depth_limit.

Another solution would be, something like this (maybe it is not so optimized):

```C++
template <typename I, typename Size, typename C, typename P>
  static void introsort(I begin, I end, Size depth_limit, C &pred,
                             P &proj) {
    if (end - begin > sort_fn::introsort_threshold()) return;
    if (depth_limit == 0) return partial_sort(begin, end, end, std::ref(pred), std::ref(proj));
    I cut = detail::unguarded_partition(begin, end, pred, proj);
    sort_fn::introsort(begin, cut, depth_limit - 1, pred, proj);
    sort_fn::introsort(cut + 1, end, depth_limit - 1, pred, proj);
  }
```

**Comment by ericniebler** [comment] 2015-05-01 21:47
Oh man. I'm sorry, you're right. &lt;facepalm&gt;

**Closed** 2015-05-02 18:35 UTC

**Comment by ericniebler** [comment] 2015-05-02 18:38
I've committed the sort_patterns benchmark from @gnzlbg and used it to run some tests. I compared my cheesy fix against another scheme where the pivot is swapped with the last element. Neither is better over all, but putting the pivot at the end causes a serious perf drop on the descending sequence test. Probably has to do with consistently choosing a bad pivot. I'll keep my silly fix.

`ranges::sort` is on par with the `std::sort` from libstdc++. However, the libc++ `std::sort` implementation is lightyears better across the board. I chose not to use it because it's really big and ugly as sin. I'm ambivalent about that decision now.

**Comment by dieram3** [comment] 2015-05-02 19:08
> Neither is better over all, but putting the pivot at the end causes a serious perf drop on the descending sequence test. Probably has to do with consistently choosing a bad pivot. I'll keep my silly fix.

Maybe you are leaving the pivot at the end and are not swapping to its correct position when partition is done. I meant something like this:
```C++
using reference = typename std::iterator_traits<RandomIt>::reference;
if(last - first < insertion_sort_threshold()) return;
auto lm1 = last - 1;
ranges::iter_swap(choose_pivot(first, last), lm1);
auto pivot_less = [lm1](reference elem){ return elem < *lm1;  };
auto pivot_it = ranges::partition(first, lm1, pivot_less);
ranges::iter_swap(pivot_it, lm1);
intro_sort(first, pivot_it);
intro_sort(pivot_it + 1, last)
```

Anyway the fix is fine, I just commented.

> ranges::sort is on par with the std::sort from libstdc++. However, the libc++ std::sort implementation is lightyears better across the board. I chose not to use it because it's really big and ugly as sin. I'm ambivalent about that decision now.

I think the current implementation is fine, the library is experimental after all. But it still has something strange: ranges::stable_sort performs faster than ranges::sort.

**Comment by ericniebler** [comment] 2015-05-02 19:17
> But it still has something strange: ranges::stable_sort performs faster than ranges::sort.

They're both taken from the SGI STL, so they were written to perform well on ancient hardware. It's entirely possible that the stable_sort implementation has better locality of reference, which matters more on modern hardware. I don't find this terribly surprising.

**Comment by ericniebler** [comment] 2015-05-02 19:19
> Maybe you are leaving the pivot at the end and are not swapping to its correct position when partition is done.

Yes, I was. But is that incorrect? It's a partition not a sort, so the pivot doesn't need to be swapped back, does it? As long as it's after the partition point, it's in its correct position.

**Comment by dieram3** [comment] 2015-05-02 19:31
> Yes, I was. But is that incorrect? It's a partition not a sort, so the pivot doesn't need to be swapped back, does it? As long as it's after the partition point, it's in its correct position.

Yes, on second thought, you're right.

**Comment by dieram3** [comment] 2015-05-02 19:44
Hmm, I was looking at the implementation of libstdc ++ and they move the pivot to the begin.
```C++ 
/// This is a helper function...
  template<typename _RandomAccessIterator, typename _Compare>
    inline _RandomAccessIterator
    __unguarded_partition_pivot(_RandomAccessIterator __first,
				_RandomAccessIterator __last, _Compare __comp)
    {
      _RandomAccessIterator __mid = __first + (__last - __first) / 2;
      std::__move_median_to_first(__first, __first + 1, __mid, __last - 1,
				  __comp);
      return std::__unguarded_partition(__first + 1, __last, __first, __comp);
    }
```
See on line 1912 [here](https://github.com/gcc-mirror/gcc/blob/master/libstdc%2B%2B-v3/include/bits/stl_algo.h)

And yes, they don't move the pivot to the partition point.
