### ISSUE TITLE
erase fails for zipped ranges

### ISSUE THREAD

**Issue by ldalessa** [ericniebler/range-v3#788] opened 2018-02-12 01:05 UTC
I'm implementing a map as two sorted vectors for key/value, and I'd like to be able to call unique and then erase, but type inferencing fails.

```C++
#include <range/v3/all.hpp>
#include <iostream>

using namespace ranges;

int main() {
  std::vector<int> key = {1, 2, 2, 3};
  std::vector<int> value = {1, 2, 0, 4};

  auto rng = view::zip(key, value);
  auto last = ranges::unique(rng, [](auto lhs, auto rhs) {
        return std::get<0>(lhs) == std::get<0>(rhs);
      });
  ranges::erase(rng, last, ranges::end(rng));
}
```

```bash
ldalessa@portland:~/temp$ clang++ --version
clang version 5.0.1-2 (tags/RELEASE_501/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
ldalessa@portland:~/temp$ clang++ -std=c++14 -I/opt/range-v3/include   test2.cpp   -o test2
test2.cpp:14:3: error: no matching function for call to object of type 'const ranges::v3::adl_erase_detail::erase_fn'
  ranges::erase(rng, last, ranges::end(rng));
  ^~~~~~~~~~~~~
/opt/range-v3/include/range/v3/action/erase.hpp:60:22: note: candidate template ignored: substitution failure [with Rng =
      ranges::v3::zip_view<ranges::v3::iterator_range<__gnu_cxx::__normal_iterator<int *, std::vector<int, std::allocator<int> > >, __gnu_cxx::__normal_iterator<int *, std::vector<int,
      std::allocator<int> > > >, ranges::v3::iterator_range<__gnu_cxx::__normal_iterator<int *, std::vector<int, std::allocator<int> > >, __gnu_cxx::__normal_iterator<int *, std::vector<int,
      std::allocator<int> > > > > &, I = ranges::v3::_basic_iterator_::basic_iterator<ranges::v3::iter_zip_with_view<ranges::v3::detail::indirect_zip_fn_,
      ranges::v3::iterator_range<__gnu_cxx::__normal_iterator<int *, std::vector<int, std::allocator<int> > >, __gnu_cxx::__normal_iterator<int *, std::vector<int, std::allocator<int> > > >,
      ranges::v3::iterator_range<__gnu_cxx::__normal_iterator<int *, std::vector<int, std::allocator<int> > >, __gnu_cxx::__normal_iterator<int *, std::vector<int, std::allocator<int> > > >
      >::cursor>, S = ranges::v3::_basic_iterator_::basic_iterator<ranges::v3::iter_zip_with_view<ranges::v3::detail::indirect_zip_fn_,
      ranges::v3::iterator_range<__gnu_cxx::__normal_iterator<int *, std::vector<int, std::allocator<int> > >, __gnu_cxx::__normal_iterator<int *, std::vector<int, std::allocator<int> > > >,
      ranges::v3::iterator_range<__gnu_cxx::__normal_iterator<int *, std::vector<int, std::allocator<int> > >, __gnu_cxx::__normal_iterator<int *, std::vector<int, std::allocator<int> > > >
      >::cursor>, _concept_requires_59 = 42, $4 = 0]: no matching function for call to 'erase'
                auto operator()(Rng && rng, I begin, S end) const ->
                     ^
/opt/range-v3/include/range/v3/action/erase.hpp:52:22: note: candidate function template not viable: requires 2 arguments, but 3 were provided
                auto operator()(Rng && rng, I it) const ->
                     ^
1 error generated.
```

Edit: I can workaround this by grabbing the difference and manually resizing the underlying arrays.
Edit: Added output.

**Comment by ericniebler** [comment] 2018-02-25 17:03
This is a dupe of #561. An interesting suggestion, but pretty far down the priority queue. Pull requests are welcome!

**Closed by ericniebler** 2018-02-25 17:03 UTC
