### ISSUE TITLE
Conflict with -fconcepts, filter view, and to_vector

### ISSUE THREAD

**Issue by adah1972** [ericniebler/range-v3#1116] opened 2019-04-02 10:20 UTC
This program fails (only) when `-fconcepts` is specified:

```c++
#include <vector>
#include <range/v3/all.hpp>

namespace ranges_v3 = ranges::v3;

auto test(int upper)
{
    using namespace ranges_v3;
    return view::iota(2, upper + 1) |
           view::filter([](int x) { return x % 2 == 0; }) |
           to_vector;
}

int main()
{
    auto v = test(20);
}
```

If I remove either `-fconcepts` or `view::filter`, compilation passes. Where is the problem?

**Comment by JeffGarland** [comment] 2019-04-03 12:11
This may be related to this earlier issue reported with gcc8.2 and -fconcepts.  Regardless I'm sure more information about compiler, environment, and failure text would be helpful.

https://github.com/ericniebler/range-v3/issues/1076

**Comment by adah1972** [comment] 2019-04-03 13:46
I think only GCC support concepts currently? Anyway, GCC 7.3 and 8.3 on Linux and Mac basically give the same error messages, so I did not bother to post.

```
test.cpp: In function 'auto test(int)':
test.cpp:10:59: error: no match for 'operator|' (operand types are 'void' and 'const ranges::v3::detail::to_container_fn<meta::quote<std::vector> >')
     return view::iota(2, upper + 1) |
            ~~~~~~~~~~~~~~~~~~~~~~~~~~                      
            view::filter([](int x) { return x % 2 == 0; }) |
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
            to_vector;
            ~~~~~~~~~                                       
In file included from ../range-v3/include/range/v3/utility/iterator_concepts.hpp:23,
                 from ../range-v3/include/range/v3/begin_end.hpp:26,
                 from ../range-v3/include/range/v3/core.hpp:17,
                 from ../range-v3/include/range/v3/all.hpp:17,
                 from test.cpp:2:
../range-v3/include/range/v3/utility/functional.hpp:725:14: note: candidate: 'template<class Arg, class Pipe, bool _concept_requires_724, typename std::enable_if<(_concept_requires_724 || ((! ranges::v3::is_pipeable<T>()) && ranges::v3::is_pipeable<Pipe>()))>::type* <anonymous> > decltype (ranges::v3::pipeable_access::impl<Pipe>::pipe(static_cast<Arg&&>(arg), pipe)) ranges::v3::operator|(Arg&&, Pipe)'
         auto operator|(Arg && arg, Pipe pipe)
              ^~~~~~~~
../range-v3/include/range/v3/utility/functional.hpp:725:14: note:   template argument deduction/substitution failed:
../range-v3/include/range/v3/utility/functional.hpp: In substitution of 'template<class Arg, class Pipe, bool _concept_requires_724, typename std::enable_if<(_concept_requires_724 || ((! ranges::v3::is_pipeable<T>()) && ranges::v3::is_pipeable<Pipe>()))>::type* <anonymous> > decltype (ranges::v3::pipeable_access::impl<Pipe>::pipe(static_cast<Arg&&>(arg), pipe)) ranges::v3::operator|(Arg&&, Pipe) [with Arg = void; Pipe = ranges::v3::detail::to_container_fn<meta::quote<std::vector> >; bool _concept_requires_724 = false; typename std::enable_if<(_concept_requires_724 || ((! ranges::v3::is_pipeable<T>()) && ranges::v3::is_pipeable<Pipe>()))>::type* <anonymous> = 0]':
test.cpp:11:12:   required from here
../range-v3/include/range/v3/utility/functional.hpp:725:14: error: forming reference to void
../range-v3/include/range/v3/utility/functional.hpp:734:14: note: candidate: 'template<class Pipe0, class Pipe1, bool _concept_requires_733, typename std::enable_if<(_concept_requires_733 || (ranges::v3::is_pipeable<T>() && ranges::v3::is_pipeable<Pipe>()))>::type* <anonymous> > decltype (ranges::v3::make_pipeable(ranges::v3::detail::composed_pipe<Pipe0, Pipe1>{pipe0, pipe1})) ranges::v3::operator|(Pipe0, Pipe1)'
         auto operator|(Pipe0 pipe0, Pipe1 pipe1)
              ^~~~~~~~
../range-v3/include/range/v3/utility/functional.hpp:734:14: note:   template argument deduction/substitution failed:
In file included from ../range-v3/include/range/v3/utility/copy.hpp:18,
                 from ../range-v3/include/range/v3/begin_end.hpp:24,
                 from ../range-v3/include/range/v3/core.hpp:17,
                 from ../range-v3/include/range/v3/all.hpp:17,
                 from test.cpp:2:
../range-v3/include/range/v3/utility/concepts.hpp:686:16: error: no type named 'type' in 'struct std::enable_if<false, void>'
     >::type* = nullptr                                                 \
                ^~~~~~~
../range-v3/include/range/v3/utility/functional.hpp:733:13: note: in expansion of macro 'CONCEPT_REQUIRES_'
             CONCEPT_REQUIRES_(is_pipeable<Pipe0>() && is_pipeable<Pipe1>())>
             ^~~~~~~~~~~~~~~~~
In file included from ../range-v3/include/range/v3/view.hpp:23,
                 from ../range-v3/include/range/v3/all.hpp:21,
                 from test.cpp:2:
../range-v3/include/range/v3/view/any_view.hpp:60:28: note: candidate: 'constexpr ranges::v3::category ranges::v3::operator|(ranges::v3::category, ranges::v3::category)'
         constexpr category operator|(category lhs, category rhs) noexcept
                            ^~~~~~~~
../range-v3/include/range/v3/view/any_view.hpp:60:28: note:   no known conversion for argument 1 from 'void' to 'ranges::v3::category'
In file included from /usr/local/Cellar/gcc/8.3.0/include/c++/8.3.0/ios:42,
                 from /usr/local/Cellar/gcc/8.3.0/include/c++/8.3.0/ostream:38,
                 from /usr/local/Cellar/gcc/8.3.0/include/c++/8.3.0/iterator:64,
                 from ../range-v3/include/range/v3/begin_end.hpp:19,
                 from ../range-v3/include/range/v3/core.hpp:17,
                 from ../range-v3/include/range/v3/all.hpp:17,
                 from test.cpp:2:
/usr/local/Cellar/gcc/8.3.0/include/c++/8.3.0/bits/ios_base.h:87:3: note: candidate: 'constexpr std::_Ios_Fmtflags std::operator|(std::_Ios_Fmtflags, std::_Ios_Fmtflags)'
   operator|(_Ios_Fmtflags __a, _Ios_Fmtflags __b)
   ^~~~~~~~
/usr/local/Cellar/gcc/8.3.0/include/c++/8.3.0/bits/ios_base.h:87:3: note:   no known conversion for argument 1 from 'void' to 'std::_Ios_Fmtflags'
/usr/local/Cellar/gcc/8.3.0/include/c++/8.3.0/bits/ios_base.h:129:3: note: candidate: 'constexpr std::_Ios_Openmode std::operator|(std::_Ios_Openmode, std::_Ios_Openmode)'
   operator|(_Ios_Openmode __a, _Ios_Openmode __b)
   ^~~~~~~~
/usr/local/Cellar/gcc/8.3.0/include/c++/8.3.0/bits/ios_base.h:129:3: note:   no known conversion for argument 1 from 'void' to 'std::_Ios_Openmode'
/usr/local/Cellar/gcc/8.3.0/include/c++/8.3.0/bits/ios_base.h:169:3: note: candidate: 'constexpr std::_Ios_Iostate std::operator|(std::_Ios_Iostate, std::_Ios_Iostate)'
   operator|(_Ios_Iostate __a, _Ios_Iostate __b)
   ^~~~~~~~
/usr/local/Cellar/gcc/8.3.0/include/c++/8.3.0/bits/ios_base.h:169:3: note:   no known conversion for argument 1 from 'void' to 'std::_Ios_Iostate'
In file included from ../range-v3/include/meta/meta.hpp:18,
                 from ../range-v3/include/range/v3/range_fwd.hpp:20,
                 from ../range-v3/include/range/v3/begin_end.hpp:23,
                 from ../range-v3/include/range/v3/core.hpp:17,
                 from ../range-v3/include/range/v3/all.hpp:17,
                 from test.cpp:2:
/usr/local/Cellar/gcc/8.3.0/include/c++/8.3.0/cstddef:145:3: note: candidate: 'constexpr std::byte std::operator|(std::byte, std::byte)'
   operator|(byte __l, byte __r) noexcept
   ^~~~~~~~
/usr/local/Cellar/gcc/8.3.0/include/c++/8.3.0/cstddef:145:3: note:   no known conversion for argument 1 from 'void' to std::byte'
In file included from /usr/local/Cellar/gcc/8.3.0/include/c++/8.3.0/bits/shared_ptr_atomic.h:33,
                 from /usr/local/Cellar/gcc/8.3.0/include/c++/8.3.0/memory:82,
                 from ../range-v3/include/range/v3/utility/functional.hpp:19,
                 from ../range-v3/include/range/v3/utility/iterator_concepts.hpp:23,
                 from ../range-v3/include/range/v3/begin_end.hpp:26,
                 from ../range-v3/include/range/v3/core.hpp:17,
                 from ../range-v3/include/range/v3/all.hpp:17,
                 from test.cpp:2:
/usr/local/Cellar/gcc/8.3.0/include/c++/8.3.0/bits/atomic_base.h:74:3: note: candidate: 'constexpr std::memory_order std::operator|(std::memory_order, std::__memory_order_modifier)'
   operator|(memory_order __m, __memory_order_modifier __mod)
   ^~~~~~~~
/usr/local/Cellar/gcc/8.3.0/include/c++/8.3.0/bits/atomic_base.h:74:3: note:   no known conversion for argument 1 from void' to 'std::memory_order'
In file included from /usr/local/Cellar/gcc/8.3.0/include/c++/8.3.0/regex:39,
                 from ../range-v3/include/range/v3/view/tokenize.hpp:17,
                 from ../range-v3/include/range/v3/view.hpp:70,
                 from ../range-v3/include/range/v3/all.hpp:21,
                 from test.cpp:2:
/usr/local/Cellar/gcc/8.3.0/include/c++/8.3.0/bitset:1438:5: note: candidate: 'template<long unsigned int _Nb> std::bitset<_Nb> std::operator|(const std::bitset<_Nb>&, const std::bitset<_Nb>&)'
     operator|(const bitset<_Nb>& __x, const bitset<_Nb>& __y) _GLIBCXX_NOEXCEPT
     ^~~~~~~~
/usr/local/Cellar/gcc/8.3.0/include/c++/8.3.0/bitset:1438:5: note:   template argument deduction/substitution failed:
test.cpp:11:12: note:   mismatched types 'const std::bitset<_Nb>' and 'void'
            to_vector;
            ^~~~~~~~~
test.cpp: In function 'int main()':
test.cpp:16:10: error: 'void v' has incomplete type
     auto v = test(20);
          ^
In file included from ../range-v3/include/range/v3/view/split.hpp:32,
                 from ../range-v3/include/range/v3/action/split.hpp:28,
                 from ../range-v3/include/range/v3/action.hpp:31,
                 from ../range-v3/include/range/v3/all.hpp:19,
                 from test.cpp:2:
../range-v3/include/range/v3/view/view.hpp: In instantiation of 'static void ranges::v3::view::view<View>::pipe(Rng&&, Vw&&) [with Rng = ranges::v3::detail::take_exactly_view_<ranges::v3::iota_view<int>, true>; Vw = ranges::v3::view::view<ranges::v3::detail::pipeable_binder<std::_Bind<ranges::v3::view::remove_if_fn_<ranges::v3::not_fn_fn>(std::_Placeholder<1>, test(int)::<lambda(int)>)> > >&; bool _concept_requires_118 = false; typename std::enable_if<(_concept_requires_118 || (! typename meta::detail::_and_<typename meta::detail::_and_<ranges::v3::concepts::models<ranges::v3::concepts::Range, Container>, typename meta::detail::_or_<std::is_lvalue_reference<Rng>, ranges::v3::concepts::models<ranges::v3::concepts::View, typename std::remove_cv<typename std::remove_reference<_SrcTuple>::type>::type> >::type>::type, ranges::v3::concepts::models<ranges::v3::concepts::Invocable, Action&, Rng> >::type()))>::type* <anonymous> = 0; View = ranges::v3::detail::pipeable_binder<std::_Bind<ranges::v3::view::remove_if_fn_<ranges::v3::not_fn_fn>(std::_Placeholder<1>, test(int)::<lambda(int)>)> >]':
../range-v3/include/range/v3/utility/functional.hpp:726:9:   required from 'decltype (ranges::v3::pipeable_access::impl<Pipe>::pipe(static_cast<Arg&&>(arg), pipe)) ranges::v3::operator|(Arg&&, Pipe) [with Arg = ranges::v3::detail::take_exactly_view_<ranges::v3::iota_view<int>, true>; Pipe = ranges::v3::view::view<ranges::v3::detail::pipeable_binder<std::_Bind<ranges::v3::view::remove_if_fn_<ranges::v3::not_fn_fn>(std::_Placeholder<1>, test(int)::<lambda(int)>)> > >; bool _concept_requires_724 = false; typename std::enable_if<(_concept_requires_724 || ((! ranges::v3::is_pipeable<T>()) && ranges::v3::is_pipeable<Pipe>()))>::type* <anonymous> = 0; decltype (ranges::v3::pipeable_access::impl<Pipe>::pipe(static_cast<Arg&&>(arg), pipe)) = void]'
test.cpp:10:57:   required from here
../range-v3/include/range/v3/view/view.hpp:125:40: error: static assertion failed: This view is not callable with this range type.
                     CONCEPT_ASSERT_MSG(Invocable<View&, Rng>(),
                                        ^~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by JeffGarland** [comment] 2019-04-03 15:08
Thanks -- I confirmed with gcc 9 (trunk compiled a few days ago) shows the same issue: works without fconcepts, but fails with fconcepts.  Also confirmed that you code works with -fconcepts on an earlier version of range library from about a year ago.  I've also run across this issue in tests I'm doing so hoping to add to the information base for a quick resolution.

**Comment by CaseyCarter** [comment] 2019-04-03 15:13
Reduces to:
```c++
#include <range/v3/view/filter.hpp>
#include <range/v3/view/iota.hpp>

static bool pred(int) { return false; }

int main() {
    ranges::view::iota(2, 4) | ranges::view::filter(pred);
}
```
Both the minimized and original programs compile without errors on v1.0-beta.

**Comment by CaseyCarter** [comment] 2019-04-03 15:23
@JeffGarland Do you have a repro? I'd like to avoid drilling down into all the metaprogramming involved in the pipe operator to root cause this if I possibly can ;)

**Comment by JeffGarland** [comment] 2019-04-03 15:28
v1 beta and gcc9 with fconcepts is still not happy, but different error this time. Interestingly gcc83 -fconcepts is happy with the v1 beta.  Should note in all cases using -std=c++2a with original code.  Not sure what you're asking on the repro, but that's all the information for at least a little while as I have to go do my day job :( 

/home/jeff/devtools/gcc9/install/usr/local/bin/g++ -I ~/devtools/range_git_v1_beta_2019_04/range-v3/include/ -std=c++2a -fconcepts fconcept_compile_error.cpp
In file included from /home/jeff/devtools/range_git_v1_beta_2019_04/range-v3/include/range/v3/iterator/concepts.hpp:20,
                 from /home/jeff/devtools/range_git_v1_beta_2019_04/range-v3/include/range/v3/iterator/operations.hpp:19,
                 from /home/jeff/devtools/range_git_v1_beta_2019_04/range-v3/include/range/v3/core.hpp:17,
                 from /home/jeff/devtools/range_git_v1_beta_2019_04/range-v3/include/range/v3/all.hpp:17,
                 from fconcept_compile_error.cpp:3:
/home/jeff/devtools/range_git_v1_beta_2019_04/range-v3/include/range/v3/range/concepts.hpp: In substitution of ‘template<class Rng, class F, class O> ranges::generate_result<typename ranges::detail::if_then<ForwardingRange_<R> >::apply<decltype (ranges::_::begin(declval<Rng&>())), ranges::dangling>, F> ranges::generate_fn::operator()(Rng&&, F) const requires  Invocable<F&> and OutputRange<Rng, decltype(ranges::invoke((declval<F&>)()))> [with Rng = std::array<unsigned int, 8>&; F = ranges::detail::randutils::get_entropy()::<lambda()>; O = unsigned int*]’:
/home/jeff/devtools/range_git_v1_beta_2019_04/range-v3/include/range/v3/utility/random.hpp:101:65:   required from here
/home/jeff/devtools/range_git_v1_beta_2019_04/range-v3/include/range/v3/range/concepts.hpp:66:28: internal compiler error: in nothrow_spec_p, at cp/except.c:1244
   66 |                 ranges::end(static_cast<T &&>(t))
      |                 ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
/home/jeff/devtools/range_git_v1_beta_2019_04/range-v3/include/concepts/concepts.hpp:222:7: note: in definition of macro ‘CPP_PP_DEF_IMPL_1_REQUIRES_BODY’
  222 |     { __VA_ARGS__; }                                                            \
      |       ^~~~~~~~~~~
/home/jeff/devtools/range_git_v1_beta_2019_04/range-v3/include/concepts/concepts.hpp:85:30: note: in expansion of macro ‘CPP_PP_CAT_’
   85 | #define CPP_PP_CAT(X, ...)   CPP_PP_CAT_(X, __VA_ARGS__)
      |                              ^~~~~~~~~~~
/home/jeff/devtools/range_git_v1_beta_2019_04/range-v3/include/concepts/concepts.hpp:213:5: note: in expansion of macro ‘CPP_PP_CAT’
  213 |     CPP_PP_CAT(CPP_PP_DEF_IMPL_1_, __VA_ARGS__)                                 \
      |     ^~~~~~~~~~
/home/jeff/devtools/range_git_v1_beta_2019_04/range-v3/include/concepts/concepts.hpp:84:30: note: in expansion of macro ‘CPP_PP_DEF_IMPL_1’
   84 | #define CPP_PP_CAT_(X, ...)  X ## __VA_ARGS__
      |                              ^
/home/jeff/devtools/range_git_v1_beta_2019_04/range-v3/include/concepts/concepts.hpp:187:5: note: in expansion of macro ‘CPP_PP_DECL_DEF_IMPL’
  187 |     CPP_PP_DECL_DEF_IMPL(                                                       \
      |     ^~~~~~~~~~~~~~~~~~~~
/home/jeff/devtools/range_git_v1_beta_2019_04/range-v3/include/concepts/concepts.hpp:84:30: note: in expansion of macro ‘CPP_PP_DECL_DEF_0’
   84 | #define CPP_PP_CAT_(X, ...)  X ## __VA_ARGS__
      |                              ^
/home/jeff/devtools/range_git_v1_beta_2019_04/range-v3/include/concepts/concepts.hpp:89:29: note: in expansion of macro ‘CPP_PP_DECL_DEF’
   89 | #define CPP_PP_EVAL(X, ...) X(__VA_ARGS__)
      |                             ^
/home/jeff/devtools/range_git_v1_beta_2019_04/range-v3/include/concepts/concepts.hpp:156:5: note: in expansion of macro ‘CPP_PP_EVAL’
  156 |     CPP_PP_EVAL(                                                                \
      |     ^~~~~~~~~~~
/home/jeff/devtools/range_git_v1_beta_2019_04/range-v3/include/range/v3/range/concepts.hpp:60:5: note: in expansion of macro ‘CPP_def’
   60 |     CPP_def
      |     ^~~~~~~
0x5e4168 nothrow_spec_p(tree_node const*)
	../../src/gcc/vec.h:987
0x5e4168 nothrow_spec_p(tree_node const*)
	../../src/gcc/cp/except.c:1236
0x870728 set_flags_from_callee(tree_node*)
	../../src/gcc/cp/call.c:334
0x870873 build_call_a(tree_node*, int, tree_node**)
	../../src/gcc/cp/call.c:369
0x87271c build_cxx_call(tree_node*, int, tree_node**, int)
	../../src/gcc/cp/call.c:9119
0x87f819 build_over_call
	../../src/gcc/cp/call.c:8662
0x883ec3 build_op_call_1
	../../src/gcc/cp/call.c:4747
0x883ec3 build_op_call(tree_node*, vec<tree_node*, va_gc, vl_embed>**, int)
	../../src/gcc/cp/call.c:4776
0xa07fdd finish_call_expr(tree_node*, vec<tree_node*, va_gc, vl_embed>**, bool, bool, int)
	../../src/gcc/cp/semantics.c:2603
0x9c2217 tsubst_copy_and_build(tree_node*, tree_node*, int, tree_node*, bool, bool)
.....

**Comment by CaseyCarter** [comment] 2019-04-03 15:48
> Not sure what you're asking on the repro

[You said](https://github.com/ericniebler/range-v3/issues/1116#issuecomment-479531047):

> I've also run across this issue in tests I'm doing

so I was hoping for a different code sample that triggers the bug.

**Comment by JeffGarland** [comment] 2019-04-03 18:05
Well there's a lot of compilers and ranges versions flying around in my world right now -- so I'm seeing all the ugly of the bleeding edge :) 

So with your minimized example, all is fine with beta1 branch, gcc82 and gcc83 with -fconcepts.  I get an error with gcc9 (trunk compile from a week ago).  Works fine without the -fconcepts.  But we could write that off as an unstable compiler and not exactly what @adah1972 reported. 

So going back to the original report I'm able to reproduce with gcc8.3, v3 trunk, and your minimized example.  Take off the -fconcepts and it compiles.

Bonus info -- cmcstl2 compiles correctly with all compilers under fconcepts.  Hopefully that narrows it down.

/home/jeff/devtools/gcc83/install/usr/local/bin/g++ fconcepts_compile_error.cpp -I ~/devtools/range_v3_2019_04/range-v3/include -std=c++2a -fconcepts
In file included from /home/jeff/devtools/range_v3_2019_04/range-v3/include/range/v3/view/remove_if.hpp:30,
                 from /home/jeff/devtools/range_v3_2019_04/range-v3/include/range/v3/view/filter.hpp:20,
                 from fconcepts_compile_error.cpp:4:
/home/jeff/devtools/range_v3_2019_04/range-v3/include/range/v3/view/view.hpp: In instantiation of ‘static void ranges::v3::view::view<View>::pipe(Rng&&, Vw&&) [with Rng = ranges::v3::detail::take_exactly_view_<ranges::v3::iota_view<int>, true>; Vw = ranges::v3::view::view<ranges::v3::detail::pipeable_binder<std::_Bind<ranges::v3::view::remove_if_fn_<ranges::v3::not_fn_fn>(std::_Placeholder<1>, bool (*)(int))> > >&; bool _concept_requires_118 = false; typename std::enable_if<(_concept_requires_118 || (! typename meta::detail::_and_<typename meta::detail::_and_<ranges::v3::concepts::models<ranges::v3::concepts::Range, Container>, typename meta::detail::_or_<std::is_lvalue_reference<Rng>, ranges::v3::concepts::models<ranges::v3::concepts::View, typename std::remove_cv<typename std::remove_reference<_SrcTuple>::type>::type> >::type>::type, ranges::v3::concepts::models<ranges::v3::concepts::Invocable, View&, Rng> >::type()))>::type* <anonymous> = 0; View = ranges::v3::detail::pipeable_binder<std::_Bind<ranges::v3::view::remove_if_fn_<ranges::v3::not_fn_fn>(std::_Placeholder<1>, bool (*)(int))> >]’:
/home/jeff/devtools/range_v3_2019_04/range-v3/include/range/v3/utility/functional.hpp:726:9:   required from ‘decltype (ranges::v3::pipeable_access::impl<Pipe>::pipe(static_cast<Arg&&>(arg), pipe)) ranges::v3::operator|(Arg&&, Pipe) [with Arg = ranges::v3::detail::take_exactly_view_<ranges::v3::iota_view<int>, true>; Pipe = ranges::v3::view::view<ranges::v3::detail::pipeable_binder<std::_Bind<ranges::v3::view::remove_if_fn_<ranges::v3::not_fn_fn>(std::_Placeholder<1>, bool (*)(int))> > >; bool _concept_requires_724 = false; typename std::enable_if<(_concept_requires_724 || ((! ranges::v3::is_pipeable<T>()) && ranges::v3::is_pipeable<Pipe>()))>::type* <anonymous> = 0; decltype (ranges::v3::pipeable_access::impl<Pipe>::pipe(static_cast<Arg&&>(arg), pipe)) = void]’
fconcepts_compile_error.cpp:13:57:   required from here
/home/jeff/devtools/range_v3_2019_04/range-v3/include/range/v3/view/view.hpp:125:40: error: static assertion failed: This view is not callable with this range type.
                     CONCEPT_ASSERT_MSG(Invocable<View&, Rng>(),
                                        ^~~~~~~~~~~~~~~~~~~~~~~

Compilation exited abnormally with code 1 at Wed Apr  3 10:43:21

**Comment by CaseyCarter** [comment] 2019-04-03 20:19
> Well there's a lot of compilers and ranges versions flying around in my world right now -- so I'm seeing all the ugly of the bleeding edge :)

It's like you're reading my mind.

**Comment by namespace-cpp** [comment] 2019-04-06 13:17
Maybe some different code sample/time interval. Compiles fine, when commenting out line containing `view::filter`:
```cpp
#include <range/v3/all.hpp>
#include <iostream>
#include <vector>

int main()
{
    namespace rg = ranges;
    using namespace rg;
    std::vector v{1,2,3,4,5,6};   
    auto r = v 
        | view::filter([](int x) { return x%2==0; })
        | view::transform([](int x) { return 3*x; }); 

    for (auto e : r) std::cout << e << ' ';
}
```
* compiles with range-v3 master (2018-12-24) with -fconcepts
* compiles with range-v3 master (2019-03-06) without -fconcepts
* fails with range-v3 master (2019-03-06) with -fconcepts
* error: no match for 'operator|' ...

compiling with g++ 8.2 -std="c++2a" as encountered 2019-06-03 locally & on wandbox.org

**Comment by ericniebler** [comment] 2019-09-11 16:29
This all compiles for me on trunk with all versions of gcc I've tested with, including gcc-8 and gcc-9. Closing.

**Closed by ericniebler** 2019-09-11 16:29 UTC
Labels: bug
