### ISSUE TITLE
view::transform with generic lambda over view::chunk doesn't compile with Clang+libc++

### ISSUE THREAD

**Issue by tonyelewis** [ericniebler/range-v3#255] opened 2015-11-26 14:11 UTC
The following example compiles correctly with `clang++ -std=c++14` but fails to compile when `-stdlib=libc++` is added. The failure is that the result of `x.front()` inside the transform's lambda can't be converted to an int.

~~~~~.cpp
#define RANGES_SUPPRESS_IOTA_WARNING
#include <range/v3/all.hpp>

#include <iostream>
#include <string>
#include <type_traits>

int main() {
	// Build view::chunk that looks like:  { { 0,1 }, { 2,3 }, { 4,5 }, { 6,7 }, { 8,9 } }
	const std::vector<int> src_rng = ranges::view::iota( 0, 10 );
	const auto             rng1    = src_rng | ranges::view::chunk( 2 );

	// Attempt to transform each inner range to a string of the first number
	const auto rng2 = rng1
		| ranges::view::transform( [] (const auto &x) {
			// *FAILS HERE* (can't convert the result of x.front() to an int)
			const int first_idx = x.front();
			return std::to_string( first_idx );
		} );
	std::cerr << rng2 << "\n";

	return 0;
}
~~~~~

I've seen similar problems using `view::group_by` as well as `view::chunk`.

Is the wrong type being deduced for the generic lambda's parameter? 

For information: all of the following snippets work without problem in the above context:

~~~~~.cpp
const int first_first_idx = rng1.front().front();
std::cerr << first_first_idx << "\n";
~~~~~

~~~~~.cpp
RANGES_FOR(const auto &x, rng1) {
	const int first_idx = x.front();
	std::cerr << first_idx << "\n";
}
~~~~~

~~~~~.cpp
ranges::v3::for_each( rng1, [] (const auto &x) {
	const int first_idx = x.front();
	std::cerr << first_idx << "\n";
} );
~~~~~

**Comment by tonyelewis** [comment] 2015-11-26 14:34
Clang compiler errors (or [downloadable coloured version](https://github.com/ericniebler/range-v3/files/45030/rv3_group_by_problem.clang_stderr.colour.txt)) :
~~~
rv3_group_by_problem.cpp:18:14: error: no viable conversion from 'range_reference_t<const ranges::v3::chunk_view<ranges::v3::range<std::__1::__wrap_iter<const int *>, std::__1::__wrap_iter<const int *> > > >' (aka 'ranges::v3::detail::take_exactly_view_<ranges::v3::range<std::__1::__wrap_iter<const int *>, std::__1::__wrap_iter<const int *> >, true>') to 'const int'
                        const int first_idx = x.front();
                                  ^           ~~~~~~~~~
/usr/include/c++/v1/type_traits:3245:17: note: in instantiation of function template specialization 'main()::(anonymous class)::operator()<ranges::v3::chunk_view<ranges::v3::range<std::__1::__wrap_iter<const int *>, std::__1::__wrap_iter<const int *> > > >' requested here
    -> decltype(_VSTD::forward<_Fp>(__f)(_VSTD::forward<_Args>(__args)...));
                ^
/usr/include/c++/v1/__config:358:15: note: expanded from macro '_VSTD'
#define _VSTD std::_LIBCPP_NAMESPACE
              ^
/usr/include/c++/v1/type_traits:3254:13: note: while substituting deduced template arguments into function template '__invoke' [with _Fp = (lambda at rv3_group_by_problem.cpp:15:30) &, _Args = <const ranges::v3::chunk_view<ranges::v3::range<std::__1::__wrap_iter<const int *>, std::__1::__wrap_iter<const int *> > > &>]
            __invoke(_VSTD::declval<_Fp>(), _VSTD::declval<_Args>()...)
            ^
/usr/include/c++/v1/type_traits:3262:11: note: in instantiation of template class 'std::__1::__invokable_imp<(lambda at rv3_group_by_problem.cpp:15:30) &, const ranges::v3::chunk_view<ranges::v3::range<std::__1::__wrap_iter<const int *>, std::__1::__wrap_iter<const int *> > > &>' requested here
          __invokable_imp<_Fp, _Args...>::value>
          ^
/usr/include/c++/v1/type_traits:3281:30: note: in instantiation of template class 'std::__1::__invokable<(lambda at rv3_group_by_problem.cpp:15:30) &, const ranges::v3::chunk_view<ranges::v3::range<std::__1::__wrap_iter<const int *>, std::__1::__wrap_iter<const int *> > > &>' requested here
    : public __invoke_of_imp<__invokable<_Fp, _Args...>::value, _Fp, _Args...>
                             ^
/usr/include/c++/v1/functional:1869:14: note: in instantiation of template class 'std::__1::__invoke_of<(lambda at rv3_group_by_problem.cpp:15:30) &, const ranges::v3::chunk_view<ranges::v3::range<std::__1::__wrap_iter<const int *>, std::__1::__wrap_iter<const int *> > > &>' requested here
    typename __invoke_of<_Ti&, _Uj...>::type
             ^
/usr/include/c++/v1/functional:2023:26: note: while substituting deduced template arguments into function template '__mu' [with _Ti = (lambda at rv3_group_by_problem.cpp:15:30), _Uj = <const ranges::v3::chunk_view<ranges::v3::range<std::__1::__wrap_iter<const int *>, std::__1::__wrap_iter<const int *> > > &>]
    return __invoke(__f, __mu(_VSTD::get<_Indx>(__bound_args), __args)...);
                         ^
/usr/include/c++/v1/functional:2086:20: note: in instantiation of function template specialization 'std::__1::__apply_functor<ranges::v3::view::transform_fn, std::__1::tuple<std::__1::placeholders::__ph<1>, (lambda at rv3_group_by_problem.cpp:15:30)>, 0, 1, std::__1::tuple<const ranges::v3::chunk_view<ranges::v3::range<std::__1::__wrap_iter<const int *>, std::__1::__wrap_iter<const int *> > > &> >' requested here
            return __apply_functor(__f_, __bound_args_, __indices(),
                   ^
range-v3/include/range/v3/view/view.hpp:97:21: note: in instantiation of function template specialization 'std::__1::__bind<ranges::v3::view::transform_fn &, std::__1::placeholders::__ph<1> &, (lambda at rv3_group_by_problem.cpp:15:30)>::operator()<const ranges::v3::chunk_view<ranges::v3::range<std::__1::__wrap_iter<const int *>, std::__1::__wrap_iter<const int *> > > &>' requested here
                    v.view_(std::forward<Rng>(rng))
                    ^
range-v3/include/range/v3/detail/config.hpp:37:15: note: expanded from macro 'RANGES_DECLTYPE_AUTO_RETURN'
    { return (__VA_ARGS__); }                                   \
              ^
range-v3/include/range/v3/utility/functional.hpp:557:42: note: in instantiation of function template specialization 'ranges::v3::view::view<ranges::v3::detail::pipeable_binder<std::__1::__bind<ranges::v3::view::transform_fn &, std::__1::placeholders::__ph<1> &, (lambda at rv3_group_by_problem.cpp:15:30)> > >::pipe<const ranges::v3::chunk_view<ranges::v3::range<std::__1::__wrap_iter<const int *>, std::__1::__wrap_iter<const int *> > > &, ranges::v3::view::view<ranges::v3::detail::pipeable_binder<std::__1::__bind<ranges::v3::view::transform_fn &, std::__1::placeholders::__ph<1> &, (lambda at rv3_group_by_problem.cpp:15:30)> > > &, 42, 0>' requested here
            pipeable_access::impl<Pipe>::pipe(std::forward<Arg>(arg), pipe)
                                         ^
range-v3/include/range/v3/detail/config.hpp:37:15: note: expanded from macro 'RANGES_DECLTYPE_AUTO_RETURN'
    { return (__VA_ARGS__); }                                   \
              ^
rv3_group_by_problem.cpp:15:3: note: in instantiation of function template specialization 'ranges::v3::operator|<const ranges::v3::chunk_view<ranges::v3::range<std::__1::__wrap_iter<const int *>, std::__1::__wrap_iter<const int *> > > &, ranges::v3::view::view<ranges::v3::detail::pipeable_binder<std::__1::__bind<ranges::v3::view::transform_fn &, std::__1::placeholders::__ph<1> &, (lambda at rv3_group_by_problem.cpp:15:30)> > >, 42, 0>' requested here
                | ranges::view::transform( [] (const auto &x) {
                ^
range-v3/include/range/v3/view_interface.hpp:238:13: note: candidate template ignored: substitution failure [with Container = int, D = ranges::v3::detail::take_exactly_view_<ranges::v3::range<std::__1::__wrap_iter<const int *>, std::__1::__wrap_iter<const int *> >, true>]: type 'int' cannot be used prior to '::' because it has no members
            operator Container ()
            ^
range-v3/include/range/v3/view_interface.hpp:246:13: note: candidate template ignored: substitution failure [with Container = int, D = ranges::v3::detail::take_exactly_view_<ranges::v3::range<std::__1::__wrap_iter<const int *>, std::__1::__wrap_iter<const int *> >, true>]: type 'int' cannot be used prior to '::' because it has no members
            operator Container () const
            ^
1 error generated.
~~~

**Comment by ericniebler** [comment] 2015-11-30 18:54
Could you try changing this:

```c++
rng1 | ranges::view::transform( [] (const auto &x) { //...
```

to this:

```c++
ranges::view::transform( rng1, [] (const auto &x) { //...
```

It looks like it could be a problem in libc++'s std::bind implementation.

**Comment by tonyelewis** [comment] 2015-11-30 19:05
Thanks for looking into this.

Yes - I've just tried the non-piped version and that compiles and runs as expected. Thanks. What does that tell you?

Might it be connected to this: http://stackoverflow.com/questions/24134735/c1y-no-viable-conversion-from-stdbind-to-stdfunction ?

**Comment by ericniebler** [comment] 2015-11-30 19:19
It tells me that the `std::bind` -- or more likely, the *`INVOKE`* -- machinery is causing the lambda's function call operator to be instantiated with the `chunk_view` on accident. It would take some work to isolate a minimal repro scenario, but I'm positive the libc++ guys would want to know about it. I suspect it is happening as an unintended side-effect during overload resolution of the `__mu` function, but without access to libc++, I can't confirm this.

That SO issue appears to be about libstdc++, so unrelated.

**Comment by tonyelewis** [comment] 2015-11-30 19:53
> That SO issue appears to be about libstdc++, so unrelated.

Ahem. :blush: Sorry about that.

> [...] I'm positive the libc++ guys would want to know about it [...]

OK. To be honest, this call stack looks pretty challenging for me to try to simplify but I'll see if can give it a go when I've got a bit of time.

Anyway - thanks for your time. I'll close this ticket; the problem seems to come from elsewhere and you've given a practical workaround too.

**Comment by gnzlbg** [comment] 2015-11-30 19:54
@tonyelewis are you using libc++ trunk?

**Comment by ericniebler** [comment] 2015-11-30 19:55
I'd rather leave it open until we have some resolution -- or at least confirmation from the libc++ guys that it's their issue. There's still a chance that my analysis is wrong and that this is a range-v3 bug.

**Comment by tonyelewis** [comment] 2015-11-30 20:23
@gnzlbg No, I'm using the version that comes with Ubuntu 15.10. _LIBCPP_VERSION is defined as 1101. That'd be a good avenue of investigation.

@ericniebler OK

**Comment by ericniebler** [comment] 2015-12-11 00:36
I can't reproduce this error with clang and libc++ built from trunk. I'm going to close this on the assumption that it is indeed a libc++ bug that has since been fixed.

**Closed by ericniebler** 2015-12-11 00:36 UTC

**Comment by tonyelewis** [comment] 2015-12-11 10:52
Apologies for lack of action - I do intend to try to look into this one a bit deeper when I get a moment. I'll post any relevant updates here.

In the meantime, thanks very much for taking the time to respond to this issue.

**Comment by tonyelewis** [comment] 2015-12-13 19:29
Yes - I can confirm that the error also disappears for me if I use a trunk libc++. Apologies that I didn't get time to check that sooner and thanks for your time on this issue.
