### ISSUE TITLE
common_iterator.hpp fails with clang 10.0-rc2: ranges::operator== has different definitions in different modules

### ISSUE THREAD

**Issue by berolinux** [ericniebler/range-v3#1438] opened 2020-02-17 01:55 UTC
Using common_iterator.hpp with clang 10.0-rc2 in C++20 mode results in
`
/usr/include/range/v3/iterator/common_iterator.hpp:267:10: error: 'ranges::operator==' has different definitions in different modules; defined here first difference is function body
    auto operator==(common_iterator<I1, S1> const & x, common_iterator<I2, S2> const & y)
    ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/range/v3/iterator/common_iterator.hpp:253:10: note: but in '' found a different body
    auto operator==(common_iterator<I1, S1> const & x, common_iterator<I2, S2> const & y)
    ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

`

**Comment by fedya** [comment] 2020-02-26 22:12
+

**Comment by ericniebler** [comment] 2020-02-26 22:29
This can only be a bug in the compiler. The two functions have different constraints. I'm guessing the constraints are not getting mangled into the name. @zygloid?

**Comment by ericniebler** [comment] 2020-02-27 02:27
Also, I'm unable to reproduce this with clang-trunk. The entire range-v3 test suite passes with `-std=c++2a`. Can you please enclose a complete repro with detailed steps?

**Comment by fedya** [comment] 2020-02-27 08:40
@ericniebler 
it is telegram-desktop build log

build list:
https://abf.openmandriva.org/build_lists/714910

just open build.log


repro:

```
docker run -ti openmandriva/cooker /bin/bash
dnf update --nogpgcheck -y
dnf install --nogpgcheck -y abb build basesystem-build
git clone https://github.com/OpenMandrivaAssociation/telegram-desktop.git
cd telegram-desktop
dnf builddep *.spec
abb build
```

**Comment by ericniebler** [comment] 2020-02-27 16:48
Can you send me something smaller and more self contained than "install docker and all this other stuff and try to build this project"? I'm not going to have time to follow your steps.

**Comment by fedya** [comment] 2020-02-27 23:07
@ericniebler 
yes, than
download archive http://file-store.openmandriva.org/api/v1/file_stores/49d69fc81eac69e40fefe1eb8c92072c2783d9d0

unpack it
than go in chroot

`sudo chroot var/lib/mock/cooker-x86_64/root/`
than 
`cd /builddir/build/BUILD/tdesktop-1.9.16-full`
ninja -C build

and you got an error

**Comment by ericniebler** [comment] 2020-02-28 00:03
If you can send me a reduced .cpp file with command line arguments and compiler version, I'm far more likely to look into this. Especially since it is 95% likely this is a clang bug, not a range-v3 bug.

**Comment by ericniebler** [comment] 2020-02-28 00:07
Closing as invalid.

**Closed by ericniebler** 2020-02-28 00:07 UTC
Labels: invalid

**Comment by fedya** [comment] 2020-02-28 00:25
this is attempt to build with gcc10, not clang

```
In file included from /home/omv/telegram-desktop/BUILD/tdesktop-1.9.16-full/build/Telegram/lib_base/CMakeFiles/lib_base.dir/cmake_pch.hxx:5:
In file included from /home/omv/telegram-desktop/BUILD/tdesktop-1.9.16-full/Telegram/lib_base/base/base_pch.h:23:
In file included from /usr/include/range/v3/all.hpp:17:
In file included from /usr/include/range/v3/action.hpp:18:
In file included from /usr/include/range/v3/action/adjacent_remove_if.hpp:22:
In file included from /usr/include/range/v3/action/erase.hpp:21:
In file included from /usr/include/range/v3/action/insert.hpp:24:
/usr/include/range/v3/iterator/common_iterator.hpp:267:10: error: 'ranges::operator==' has different definitions in different modules; defined here first difference is function body
```

**Comment by ericniebler** [comment] 2020-02-28 00:47
> different definitions in different modules

To the best of my knowledge, gcc-10 doesn't support modules. The "different definitions in different modules" is a clang error, as far as I'm aware.

I need a minimal, self-contained repro, or I can't help you. Preprocessed input, compiler version, and flags, please.
