### ISSUE TITLE
problems with custom views, const and remove_if

### ISSUE THREAD

**Issue by mgaunard** [ericniebler/range-v3#428] opened 2016-07-06 17:12 UTC
I've built a simple custom view with view_facade.
Whenever I pipe its ouput to view::remove_if and bind the result to a const reference, I become unable to call .begin() on it (it works fine with a non-const rvalue reference)
It works fine if remove_if is replaced by another adaptor like view::transform.
I tried to look at what happens, but it's a complex dance between begin and range_access::begin_cursor.

Minimal reproducer

```C++
#include <range/v3/all.hpp>

struct my_range : ranges::view_facade<my_range>
{
private:
    friend ranges::range_access;

    struct cursor
    {
        int get() const
        {
            return 0;
        }

        bool equal(cursor const&) const
        {
            return true;
        }

        void next()
        {
        }
    };

    cursor begin_cursor() const { return cursor(); }
    cursor end_cursor()   const { return cursor(); }
};

int main()
{
    auto const& rng = my_range() | ranges::view::remove_if([](auto&&) { return false; });
    auto it = rng.begin();
}
```

I might be doing things wrong, but in any case the error message is not helpful at all.

**Comment by CaseyCarter** [comment] 2016-07-06 21:09
`view::remove_if` caches mutable state, and is thus a mutable-only view. It does not have `const` `begin` or `end`. Compositions of other views with mutable-only views are necessarily mutable-only. (There's a very detailed discussion of what `const` means for `View`s in issue #385.)

I do agree that we could improve the diagnostic here.

**Comment by mgaunard** [comment] 2016-07-06 22:12
How is it any different than transform?
In both of these, the only state is the function object.

(If it matters, my function object was also stateless)

**Comment by CaseyCarter** [comment] 2016-07-06 22:32
> How is it any different than transform?

`remove_if` caches the value of the first "non-removed" iterator in the range so as to amortize the cost of multiple calls to `begin` since `begin` is supposed to be O(1). This is odd given that `next` and `prev` are *not* O(1) and more likely to be called frequently and repeatedly, but that's currently the way things stand.

**Comment by ericniebler** [comment] 2016-07-09 22:19
Duplicate of #385.

**Closed by ericniebler** 2016-07-09 22:19 UTC

**Comment by tonyelewis** [comment] 2018-03-01 21:38
Tagging connection to #254.
