### ISSUE TITLE
"stack trace" like information for concept failure

### ISSUE THREAD

**Issue by Manu343726** [ericniebler/range-v3#175] opened 2015-06-16 22:05 UTC
Despite the fact range does a great job at constraining algorithm inputs with concepts (Seriously, the interface of the lib is so consistent, I'm sure modeling all the concepts took a lot of work), when something fails I usually find quite hard to know what exact property/rule of the concept was missing on my datatype. 

Consider this example: I start writing some kind of range type from scratch, with its own `begin()` and `end()` member functions:

``` cpp
struct myrange
{
    using iterator = ...;

    iterator begin() const
    {
        return ...;
    }

    iterator end() const
    {
        return ...;
    }
};
```

After testing the custom range type via a range for

``` cpp
for(auto e : myrange{...})
    std::cout << e;
```

everything seems to work as expected, so it's time to apply views on it:

``` cpp
auto view = myrange{...} | ranges::view::transform([](const auto& e){ return ...;});
```

but Range lib says my range cannot be piped since is not a model of the `Iterable` concept. To find what the custom range is missing, the only current alternative (since lack of docs, what of course I totally understand and is not the reason for this issue) is to dive into the concept definition, looking  across all the refinements, etc.  
After my long voyage across range sources I was able to get the property the iterator was missing and fix my problem. 

This and similar experiences while playing with Range give me an idea: **What if Concepts carry all the semantic information needed to produce an informative and human readable error message?**
That could improve UX a lot. This is the (ideal) error message I would like to see in the example above:

```
line X: Static assertion failed: The type Rng must be a model of the Iterable concept.
    Iterable: requires "begin(t), end(t)" model "IteratorRange"
        IteratorRange: requires "I" model "Iterator"
                Iterator: refines "WeakIterator", "Semiregular"
                    WeakIterator: refines "WeaklyIncrementable", ...
                        WeaklyIncrementable: refines "Semiregular"
                            SemiRegular : refines ...
                            SemiRegular: requires "&t" of type "T*"
                        WeaklyIncrementable: requires TRUE "std::is_integral<difference_t<I>>{}"
                        WeaklyIncrementable: requires "++i" of type "I&"
                    WeakIterator: requires "*i"
        IteratorRange: requires "S" model "Regular"
            Regular: ...
            ...
        IteratorRange: requires "I, S" model "EqualityComparable"
            EqualityComparable: ...
            ...
```

As you can see, the error message contains **all the semantic and syntactic features required by the main concept**, you just have to follow the "stack trace" of concepts. A kind of *"compile-time uncaught exception"*.

The funny part is that most of this information is already encoded in the concepts implementation itself, we just have to provide a way to capture the atomic items (Those enclosed at the `requires` clauses with "") then concat all the information messages recursively.  
This needs to restructure all the concept implementation from its base: The elements of `valid_expr()` suitable to be SFINAEd  to check for expression correctness (let's call them *checkers*)  need to have both the expression itself and its stringfied version for the error message. Then `valid_expression()` needs to concat those strings in addition to be sfinaed. The final error message of a concept is the sum of the string from its `requires` function and those from the concepts it refines. The whole design looks like a monad holding a tuple (String, SFINAE-able thing) for each check and concept.

I will be glad to spend this summer working on this topic if you find it interesting/useful. This applies to all the libraries relying on C++11 concepts checking out there, like @ldionne's Hana or @pfultz2's Tick.

**Comment by pfultz2** [comment] 2015-06-16 23:32
This was discussed [here](https://github.com/ericniebler/range-v3/issues/94) with this issue already. 

> This needs to restructure all the concept implementation from its base: The elements of valid_expr() suitable to be SFINAEd to check for expression correctness (let's call them checkers) need to have both the expression itself and its stringfied version for the error message. Then valid_expression() needs to concat those strings in addition to be sfinaed. The final error message of a concept is the sum of the string from its requires function and those from the concepts it refines. The whole design looks like a monad holding a tuple (String, SFINAE-able thing) for each check and concept.

This doesn't work well with composing other concepts, because you would need to concat strings. `enable_if`(or `static_assert`) only allows a string literals, you can't put a `constexpr` string there. Also, it still is not very helpful. What the user needs is a list of just the expressions that failed.

> I will be glad to spend this summer working on this topic if you find it interesting/useful.

Actually, time would be better spent improving diagnostics in clang. I started the work [here](http://reviews.llvm.org/D8309)(I haven't had time to finish the patch yet). I also started work with parsing `enable_if` boolean expression(which I haven't submitted yet) to show the individual trait that failed(similar to how concepts lite work an Andrew Suttons branch) I can send you the initial code offline if you like. Most of it is fairly trivial.

The biggest part that needs to happen is refactoring in clang so that a tree of overload resolution failures could be generated(right now clang squashes the sfiane backtrace every chance it gets). Then the compiler can use that overload resolution tree to diagnose why a certain trait was false. So, then it will be possible for the compiler to generate an error close to this:
```
main.cpp:7:1: error: no matching function for call to object of type ‘const for_each_fn’

range-v3/include/range/v3/algorithm/for_each.hpp:49:15: note: candidate template ignored: disabled by 'enable_if' [with Rng = DataFrame, F = lambda at main.cpp:7:1, P = ident]
    CONCEPT_REQUIRES_(InputRange<Rng>() && IndirectCallable<F, Project<I, P>>())>
                      ^

range-v3/include/range/v3/algorithm/for_each.hpp:49:15: note: InputRange<DataFrame>() trait failed
    CONCEPT_REQUIRES_(InputRange<Rng>() && IndirectCallable<F, Project<I, P>>())>
                      ^

DataFrame.h:32:7: error: Indirection requires pointer operand (‘const I’ (aka ‘const RowIterator<self_t>’) invalid) [with I = DataFrameIterator]
```

Which will give more information to the user than concepts lite does currently in gcc.

**Comment by ericniebler** [comment] 2015-06-18 17:06
Closing this as a dupe of #94

**Closed by ericniebler** 2015-06-18 17:06 UTC
