### ISSUE TITLE
View adaptor update destroyed compilation times

### ISSUE THREAD

**Issue by FloopCZ** [ericniebler/range-v3#758] opened 2017-12-01 00:24 UTC
Hi everyone,

In the place where I work, we have a larger project utilizing `range-v3` heavily. The project takes about 4 minutes and 20GB of RAM to compile with clang++-5.0 (`--std=c++17`). Unfortunately, after 25f7db1d96968e1d19b8f4109560efea4c3b8a02 (found with `git bisect`) it takes at least 30 minutes to compile (to be honest, I never waited till the end actually :-)) and eats about 40GB of memory. Do you have any idea what could cause such a difference (@CaseyCarter)? I cannot see anything that evil in the commit.

(relates to https://github.com/ericniebler/range-v3/issues/332)

Thank you!

**Comment by ericniebler** [comment] 2017-12-01 00:53
Interesting! What is your compiler/version?

This diff adds a slew of conditional `noexcept` in some significant places. I wonder if that's the problem. Could you try something for me? Edit your `config.hpp` locally to make the definition of `RANGES_DECLTYPE_AUTO_RETURN_NOEXCEPT` the same as that of `RANGES_DECLTYPE_AUTO_RETURN` and then re-measure.

By extension, I suspect that replacing trailing return types with deduced return types (in C++ >= 14)  would result in perf wins. That couldn't be done willy-nilly since the trailing return types are sometimes used to SFINAE.

**Comment by FloopCZ** [comment] 2017-12-01 01:18
I obviously cannot provide the original code, but the issue seems to be partially reproducible with [cxtream unit tests](https://cxtream.org/). Following the [installation guide](https://cxtream.org/installation.html):
```
git clone --recursive https://github.com/Cognexa/cxtream.git
cd cxtream/third_party/range-v3

# checkout one of the following:
git checkout 3cda7846caa253a8d2b136879d392b0f2d64cf3e
git checkout 25f7db1d96968e1d19b8f4109560efea4c3b8a02

cd ../../ && mkdir build && cd build
cmake -DCMAKE_CXX_COMPILER=clang++ ..
/usr/bin/time -v make -j1
```
On range-v3 3cda7846caa253a8d2b136879d392b0f2d64cf3e (one before 25f7db1d96968e1d19b8f4109560efea4c3b8a02):
```
        User time (seconds): 347.33
        Maximum resident set size (kbytes): 2141416
```

On range-v3 25f7db1d96968e1d19b8f4109560efea4c3b8a02
```
        User time (seconds): 549.32
        Maximum resident set size (kbytes): 4017480
```

**Comment by FloopCZ** [comment] 2017-12-01 01:48
Thank you for your fast reply.

> Could you try something for me? Edit your config.hpp locally to make the definition of RANGES_DECLTYPE_AUTO_RETURN_NOEXCEPT the same as that of RANGES_DECLTYPE_AUTO_RETURN and then re-measure.

Sure. :-) The results seem to be very slightly better (tried twice and it does not seem to be only a measurement noise, especially the memory consumption):
```
        User time (seconds): 515.63
        Maximum resident set size (kbytes): 3839376
```

**Comment by CaseyCarter** [comment] 2017-12-01 03:16
Could you try reverting just the the `view_interface` stream operator overload changes, basically everything after [line 346 of `view_interface.hpp`](https://github.com/ericniebler/range-v3/commit/25f7db1d96968e1d19b8f4109560efea4c3b8a02#diff-6eb80fe25ad793af67b77375d1d8b075R346)? There's a few different things going on there that could contribute to overload resolution blowup.

**Comment by ericniebler** [comment] 2017-12-01 17:11
@CaseyCarter: although it's not the culprit here, it's interesting to note that removing the conditional `noexcept`s makes an example program compile 6% faster. This argues against adding conditional `noexcept` willy-nilly. I'd like to walk back many of our uses of `noexcept`.

**Comment by FloopCZ** [comment] 2017-12-01 22:13
@CaseyCarter Sorry for the delay. I tried this and the compilation time seems to remain unchanged. The ostream overloads are not used in our projects.
```
        User time (seconds): 538.25
        Maximum resident set size (kbytes): 4017824
```

**Comment by ericniebler** [comment] 2017-12-08 22:59
@CaseyCarter i'm assigning to you since your diff caused the regression. i don't feel like i can officially cut a new range-v3 release with this big of a compile time regression.

**Comment by CaseyCarter** [comment] 2017-12-10 23:26
I should (finally) have some time to investigate this week.

**Comment by CaseyCarter** [comment] 2017-12-12 03:13
## On the value of constraining with concepts over constraining with return type SFINAE:

If you glance at the PR, you'll find that the 60% increase in compile time was caused by the removal of a single concept constraint: `Range<base_range_t const>()`. This constraint is "unnecessary" since the return type of the functions in question - `view_adaptor::begin_cursor() const` and `view_adaptor::end_cursor() const` - is a template alias that fails substitution when the constraint does not hold. So why not remove it, right?

Apparently compilers (clang) do *not* cache the result of alias template substitutions that *fail*. Wrapping such substitutions up into a concept-style constraint so that failures are cached - even range-v3's emulated concepts - has enormous performance impact. 

I'm feeling really happy about the decision to constrain *everything* in cmcstl2 with concepts and avoid return-type SFINAE.

We should consider auditing range-v3 for similar occurrences where templates are constrained via return type SFINAE on an alias template.

**Comment by gnzlbg** [comment] 2017-12-12 07:23
> Apparently compilers (clang) do not cache the result of alias template substitutions that fail. 

!!! Is there a clang bug for this open?

**Comment by FloopCZ** [comment] 2017-12-12 12:24
@CaseyCarter Wow! Good job identifying the issue, this one was tricky! I can confirm that with #761 the original compilation times are back (resp. they are only 1-2% slower).

> We should consider auditing range-v3 for similar occurrences where templates are constrained via return type SFINAE on an alias template.

:+1:

**Comment by CaseyCarter** [comment] 2017-12-12 16:48
> !!! Is there a clang bug for this open? (or can you post it here if you open one?)

I haven't opened a bug since I haven't yet devised an experiment to verify my hypothesis / provide a repro. I would hate to attach a preprocessed repro that contains substantial portions of range-v3, cxtream, and boost to a bug report that would be effectively "something in these millions of lines of code is slow."

**Closed** 2017-12-12 17:48 UTC

**Comment by ericniebler** [comment] 2017-12-12 17:51
A million thanks @CaseyCarter for finding and fixing this!
