### ISSUE TITLE
Bug Report: [v3.0.10.0] ranges::to doesn't work on std::move_iterator range

### ISSUE THREAD

**Issue by yaoxinliu** [ericniebler/range-v3#1475] opened 2020-04-25 08:19 UTC
```
#include <range/v3/all.hpp>
#include <vector>
#include <string>
#include <deque>
#include <iostream>

using namespace std;
using namespace ranges;
using namespace std::literals;

int main()
{
    auto src = vector{"abc"s, "xyz"s};
    auto rng = subrange(std::make_move_iterator(src.begin()), 
                        std::make_move_iterator(src.end()));

    auto dst = to<deque<string>>(rng);
    for (auto e : src)
    {
        cout << e.size() << e << endl;
    }

    for (auto e : dst)
    {
        cout << e.size() << e<< endl;
    }
}
```
Compiled with `clang++ -std=c++20 -stdlib=libc++ main.cpp`, and the output is:

> 3abc
> 3xyz
> 3abc
> 3xyz

I think the correct output should be:

> 0
> 0
> 3abc
> 3xyz

I have also run the same code above at [godbolt.org](https://godbolt.org/), however, the result there is as expected. I suspect the version of `ranges` [godbolt.org](https://godbolt.org/) installed differs from `v3.0.10.0`.

**Comment by dvirtz** [comment] 2020-04-26 20:04
The version is just `0.10.0`, `v3` is part of the library name. You can select the version in godbolt and indeed the bug reproduces on `0.10.0` but is seems to be fixed on trunk.

**Comment by ericniebler** [comment] 2020-04-26 22:16
Moved-from strings have a valid but unspecified state. The behavior you are seeing is due to the Small String Optimization. If you use longer strings in your test, I certain you'll see the behavior you expect.

**Closed by ericniebler** 2020-04-26 22:16 UTC
