### ISSUE TITLE
Tests fail to build with the latest clang

### ISSUE THREAD

**Issue by yurivict** [ericniebler/range-v3#790] opened 2018-02-16 17:54 UTC
Got this on FreeBSD 12:

```
/wrkdirs/usr/ports/devel/range-v3/work/range-v3-0.3.0/include/range/v3/utility/invoke.hpp:106:41: error: redundant parentheses surrounding declarator [-Werror,-Wredundant-parens]
            constexpr auto operator()(F (Obj::*ptr), First && first, Rest &&... rest) const
                                        ^~~~~~~~~~~
/wrkdirs/usr/ports/devel/range-v3/work/range-v3-0.3.0/include/range/v3/utility/invoke.hpp:115:44: error: redundant parentheses surrounding declarator [-Werror,-Wredundant-parens]
            constexpr auto operator()(Data (Obj::*ptr), First && first) const
                                           ^~~~~~~~~~~
/wrkdirs/usr/ports/devel/range-v3/work/range-v3-0.3.0/include/range/v3/utility/invoke.hpp:106:41: error: redundant parentheses surrounding declarator [-Werror,-Wredundant-parens]
            constexpr auto operator()(F (Obj::*ptr), First && first, Rest &&... rest) const
                                        ^~~~~~~~~~~
/wrkdirs/usr/ports/devel/range-v3/work/range-v3-0.3.0/include/range/v3/utility/invoke.hpp:115:44: error: redundant parentheses surrounding declarator [-Werror,-Wredundant-parens]
            constexpr auto operator()(Data (Obj::*ptr), First && first) const
                                           ^~~~~~~~~~~
2 errors generated.
```

**Comment by ericniebler** [comment] 2018-02-16 18:11
Past time, yes. I've just been so busy. :-P Let me get the paper on the improved `begin`/`end` CPOs written, and then I'll roll a new release.

**Comment by CaseyCarter** [comment] 2018-02-16 18:14
> Past time, yes. I've just been so busy.

I suppose I really meant to say, "Are there any remaining release-blocking issues?" to make sure you weren't waiting on me to fix something. I'll close this issue as "fixed pending release."

**Closed by CaseyCarter** 2018-02-16 18:14 UTC

**Comment by ericniebler** [comment] 2018-02-16 18:17
> Are there any remaining release-blocking issues?

No, not since you fixed that compile time regression.

**Comment by yurivict** [comment] 2018-02-16 18:21
Yes, please make a release.
