### ISSUE TITLE
range-v3 should be /W4-clean on MSVC

### ISSUE THREAD

**Issue by MikeGitb** [ericniebler/range-v3#939] opened 2018-11-19 17:45 UTC
When I compile a simple program like this:

	#include <range/v3/algorithm.hpp>
	#include <vector>

	int main()
	{
		std::vector<int> v{3, 2, 5, 8, 6, 6, 1, 6, 2};
		ranges::sort( v );
	}

 with VS2017 15.9 with W4, I get a lot of warnings along the lines of 

>[...] range\v3\algorithm\sort.hpp(92): warning C4459: declaration of 'next' hides global declaration
  [...] range/v3/utility/iterator.hpp(265): note: see declaration of 'ranges::v3::next'

While this is certainly not a bug, it would be nice, if the ranges-v3 headers would compile warning free on a "reasonable warning level" (and yes, I consider W4 to be reasonable, but of course you might disagree).

**Comment by CaseyCarter** [comment] 2018-11-19 18:48
We're currently only `/W3` clean. `/W4` is on my TODO list, and probably `/Wall` / `-Weverything`.

**Comment by robert-andrzejuk** [comment] 2019-05-13 18:59
The variable `data` is inside an inline namespace, so I'm unsure about this...
Is this a MSVC bug (and I should report a bug there) or a can I submit a merge request here?

    1> \range-v3\include\range\v3\detail\variant.hpp(706,1): warning C4459:  declaration of 'data' hides global declaration
    1> \range-v3\include\range\v3\detail\variant.hpp(706,1): warning C4459:         {
    1> \range-v3\include\range\v3\detail\variant.hpp(706,1): warning C4459: ^
    1> \range-v3\include\range\v3\data.hpp(84,13): message :  see declaration of 'ranges::v3::CPOs::data'
    1> \range-v3\include\range\v3\data.hpp(84,13): message :             RANGES_INLINE_VARIABLE(data_detail::data_fn, data) 
    1> \range-v3\include\range\v3\data.hpp(84,13): message :             ^

**Comment by silverqx** [comment] 2021-08-20 10:12
Would be good to fix this **C4459** warning when the client project uses **/W4**, this is only one warning which is produced with the **/W4** flag.

**Comment by silverqx** [comment] 2021-08-20 10:40
I looked at it and the problem is [here](https://github.com/ericniebler/range-v3/blob/0487cca29e352e8f16bbd91fda38e76e39a0ed28/include/range/v3/algorithm/sort.hpp#L103)

It can be fixed by renaming the local variable from `next` to eg `next_`, I can propose PR.

What local variable name do you prefer? @ericniebler

**Comment by ericniebler** [comment] 2021-08-20 14:35
`next_` is fine. Thanks!

**Closed** 2021-08-21 05:17 UTC
Labels: enhancement
