### ISSUE TITLE
"meta" conflicts with ncurses

### ISSUE THREAD

**Issue by dstahlke** [ericniebler/range-v3#473] opened 2016-09-17 21:00 UTC
I'm not sure whether you want to rename this late in the game, but your "meta" namespace conflicts with a function by the same name declared by ncurses.  Consequently, ncurses and ranges-v3 cannot both be used in the same compilation unit.

**Comment by CaseyCarter** [comment] 2016-09-17 21:02
This issue is a duplicate of ericniebler/meta#36.

**Comment by ericniebler** [comment] 2016-10-04 23:33
The answer there, for reference, is (by @gnzlbg):

> So I've asked this on SO: http://stackoverflow.com/questions/37393414/name-collision-between-c-library-namespace-and-c-linux-function
>
> Seems that your best bet is to use the ncurses c++ bindings. If they are not shipped by your distribution they should be inside the ncurses source directory.

**Closed by ericniebler** 2016-10-04 23:33 UTC

**Comment by jmille01** [comment] 2017-04-04 13:05
I really wanted to introduce ranges-v3 into my codebase but also ran into issues with name collisions with meta.  I started trying factor out collisions with ncurses and then ran into a collision somewhere else.  I know you've moved on here but I wish you would consider hiding the "meta" namespace.  That is just too general a name.

**Comment by gnzlbg** [comment] 2017-04-04 13:40
@jmille01 

Are you using the `ncurses` library? If so, why aren't you using the C++ bindings? If not, can you try to find out where the collision is coming from?

BTW this is a known problem with clang modules on MacOSX ([llvm-bug:32192](https://bugs.llvm.org//show_bug.cgi?id=32192)), where all system components including the ncurses C headers are always pulled in by default, and there is no way to only pull in the system modules that you actually want to use (its all or nothing).

**Comment by jmille01** [comment] 2017-04-04 14:19
I'm not using the C++ bindings because I have existing code that doesn't use the C++ bindings.  There is some historical reason for that, but regardless it doesn't make sense to track down and rewrite all of that in order to start using ranges-v3.  "ranges-v3" is a very nice low-collision namespace and I would love to pull it in and start getting other users here familiar with the paradigm but I can't justify the time expenditure to make it usable because of the "meta" name conflicts.

**Comment by gnzlbg** [comment] 2017-04-04 14:41
@jmille01 are you using both in the same TU ? If not you might be able to work around this _for now_.

I guess it could be possible to "include" `meta` headers inside the `ranges` namespace without major breakage, and provide a macro to switch behavior. @ericniebler ?

**Comment by dstahlke** [comment] 2018-06-24 23:04
This works:

```
#define meta meta_disabled
#include <ncurses.h>
#undef meta
```
