### ISSUE TITLE
How stable are current interfaces, will there be releases?

### ISSUE THREAD

**Issue by h-2** [ericniebler/range-v3#560] opened 2017-02-01 17:20 UTC
We are currently discussing a major re-design of a generic c++ library. We would really like to use range-v3, but some things are not yet clear to us:
  * how much change does the library currently undergo?
  * how much of this change breaks previous interfaces?
  * does it adhere strictly to N4128 or does it go beyond it?
  * will there be releases of the library that we could target?

Thanks very much for publishing and maintaining this code!

**Comment by gnzlbg** [comment] 2017-02-01 17:56
Only @ericniebler can give you the official statement, but I have been using the library in production for ~3 years and can give you my experience:

> how much change does the library currently undergo?

- There is not _a lot_ of breakage, common things (algorithms, views, actions) haven't caused breakage in a long time (a year maybe? I cannot recall the last time something broke here).
- Changes to the utilities do cause breakage "often" (~1 per month). The utilities are very useful though, range-v3 can replace a big part of boost (concepts, concept checking, meta, tuple algorithms, optional, variant, ...) 

> how much of this change breaks previous interfaces?

See above.

> does it adhere strictly to N4128 or does it go beyond it?

- Not strictly, but enough not to really need to care about this as a user. It adds views and actions which are very useful (and will be part of future papers).

> will there be releases of the library that we could target?

This project target master on every configure, that is, it updates range-v3 multiple times per day... When breakage occurs at unfortunate times where we cannot try to fix things immediately, we fix a commit hash from ~2 days ago until the issue is resolved, and then back to tracking master.

That is, even if there aren't fixed releases of the library, you can probably jus choose a commit, and stick to "that version". Whenever you have time to upgrade you can try to track master again, and if it works you can update the hash, or fill an issue if it doesn't (or try to figure out why).

**Comment by h-2** [comment] 2017-02-01 18:29
> Only @ericniebler can give you the official statement, but I have been using the library in production for ~3 years and can give you my experience

Thanks for your reply!

> Changes to the utilities do cause breakage "often" (~1 per month). The utilities are very useful though, range-v3 can replace a big part of boost (concepts, concept checking, meta, tuple algorithms, optional, variant, ...)

We will likely be targeting C++17 and the Concepts TS so we will probably not need to make use of the utilities too much.

> That is, even if there aren't fixed releases of the library, you can probably jus choose a commit, and stick to "that version". Whenever you have time to upgrade you can try to track master again, and if it works you can update the hash, or fill an issue if it doesn't (or try to figure out why).

I am not worried about finding smaller issues, but we have to consider downstream users of the library, as well. It would be really good to be able to say that our library depends on `range-v3-0.x.y or greater` or at least `exactly range-v3-0.x.y`. I know that from a developer's point of view a git hash is not much different, but for proper deployment it is not enough.

**Comment by gnzlbg** [comment] 2017-02-01 22:41
> range-v3-0.x.y or greater or at least exactly range-v3-0.x.y. I know that from a developer's point of view a git hash is not much different, but for proper deployment it is not enough.

Yes if you are distributing your library/binary for your users to compile it, this is a real issue. The problem is, however, that you cannot say range-v3-0.x.y "or greater", but rather "greater than X and smalleer than Y" due to semantic versioning.... and if one of your clients relies on 2 libraries with different requirements and need to operate between them they are basically screwed and there is no way to find common ground easily in C++ (in particular with header only libraries). This is a real painful issue. 

Doing releases that respect semantic versioning take a lot of effort and work. I am not saying it is not worth it, but currently the concepts are still changing "a bit". Even if these changes don't impact you as an user much (or at all), they are still API breaking changes if you are following semantic versioning (which is the only reasonable thing to do). So... this results in every single "release" being completely backwards incompatible with the previous one...

**Comment by h-2** [comment] 2017-02-02 10:40
Of course we will do semantic versioning for our library so the best solution for us would be for range-v3 to be semantically versioned as well, although I see why this is difficult right now.

However some form of non-semantic regular or irregular releases would still be better than none at all. Say if there were two releases per year in the form of 0.YY.MM that would already make life a lot easier for us. We could then target explicit versions and in some cases maybe adopt hacks to make our library work with different versions of range-v3 in case it introduces incompatibilities.

@ericniebler could you comment on whether something like this would be possible in the future?

Thanks a lot!

**Comment by gnzlbg** [comment] 2017-02-02 10:53
@ericniebler FWIW the "cost" of doing 0.y.z releases using semantic versioning is low:

- Just `git tag 0.y.z && git push origin master` (replacing y and z with numbers) and github does the rest (adds a release page that shows all releases and packages them in compressed format for download). 
- [Semantic versioning for 0.y.z](http://semver.org/#spec-item-4) means that any new version can be API breaking (so one does not need to commit to anything).

**Comment by ericniebler** [comment] 2017-02-02 22:15
Possible, but as @gnzlbg says every commit is potentially API breaking at this point. Range-v3 tracks the progress of the Ranges TS through the standardization committee, so it's not entirely under my control.

I guess I could tag commits, but the tags would be as meaningless as the commit hash so I've avoided doing it. A release page on github sounds nifty, so maybe it's worth doing.

**Comment by h-2** [comment] 2017-02-07 12:31
@ericniebler Thanks for your reply and for considering adding release tags! I do think two tagged commits like `0.17.4`  or `0.201704` per year would really help people, just so that they could target something. 

I don't know if there is a `__cpp_ranges` macro (or similar), but it would make a lot of sense if this could be set to correspond to these dates so that code using the library can also check this. Would this be possible? I know it's more work that just tagging the commit, but it would only need to be bumped before / after the releases and I see no other obvious way to detect version mismatch.

Thank you very much!

**Comment by ericniebler** [comment] 2017-03-08 23:06
> We are currently discussing a major re-design of a generic c++ library. We would really like to use range-v3, but some things are not yet clear to us:
>  * how much change does the library currently undergo?

It's been pretty stable for a while, but I'm currently working on a series of breaking interface changes to bring range-v3 in line with the current wording of the Ranges TS (plus approved changes).

>  * how much of this change breaks previous interfaces?

It should be a minor breakage -- if at all -- for folks consuming the interfaces. For those *extending* the interfaces, the breakages will be more substantive.

>  * does it adhere strictly to N4128 or does it go beyond it?

Neither and both. The current draft of the Ranges TS says nothing about views and actions, so clearly range-v3 goes quite a ways beyond N4128. And the draft of the Ranges TS has also evolved away from N4128, and it continues to evolve.

The upcoming changes (currently living in the ranges-ts branch) will harmonize the library with the current draft plus approved changes. It will continue to evolve along with the draft, and as I spot and squash differences.

>  * will there be releases of the library that we could target?

Yes! See the semantic-versioning branch. When I merge that, the version will be 0.1.0 (and it's tagged appropriately). When I merge the ranges-ts, branch, I'll bump the minor version, since it's a breaking change.

I've also added macros for `RANGE_V3_MAJOR`, `RANGE_V3_MINOR`, and `RANGE_V3_PATCHLEVEL`. I have CMake magic to keep it all in sync.

**Closed** 2017-03-08 23:15 UTC

**Comment by h-2** [comment] 2017-03-09 22:48
Thanks a lot! :tada: :fireworks:
