### ISSUE TITLE
view/iota over opaque integers

### ISSUE THREAD

**Issue by LucHermitte** [ericniebler/range-v3#514] opened 2016-11-22 18:46 UTC
I've defined opaque (aka strong) typepefs over integers in order to avoid stupid mistakes (like mistaking row and column indices) -- and in order to experiment with the concept I must admit. I took the road of using `enum class`es complemented with all the needed binary arithmetic operators and increment operators -- I haven't experimented with [other approaches](https://sourceforge.net/p/opaque-typedef/wiki/Home/), but I expect similar results.

```C++
enum class row_t = long long;
enum class row_offset_t = long long;

row_t operator+(row_t, row_offset_t);
row_t operator+(row_offset_t, row_t);
row_offset_t operator+(row_offset_t, row_offset_t);

row_offset_t operator-(row_t, row_offset_t); // non commutative
row_offset_t operator-(row_t, row_t);
row_offset_t operator-(row_offset_t);

row_t &operator++(row_t &);
row_t operator++(row_t &, int);
```

Then I was expecting to be able to use them along with `view::ints(row_t(0), row_t(42));`. Alas there are a few blocking issues. The first one being that enum classes are not _integral_ per standard specification, and we cannot tell otherwise -- my issue is closely related to #356, if not the same.

If we could register `row_t` to be integral (I know there is no such variation point at this time in range-v3, but I've still specialized `std::is_integral<>` to see what happens next), the second problem is that the offset type shall be `long` (or any other integral type). I haven't been able to use another opaque type like `row_offset_t`.

IMO, it would be nice for `view::ints()` and `iota()` to support opaque types over integral types. But I cannot tell what really needs to be changed: should the `Integral` concept be defined differently and opened to new integral types? Or should the requirement in `ints()` be relaxed? (Or did I miss another way to proceed?)

**Comment by ericniebler** [comment] 2016-11-22 19:51
`view::ints` requires actual integers, but `view::iota` requires only `WeaklyIncrementable`. The only requirement you're missing is that the difference type (the result of subtraction) be integral, as you've noticed. Unfortunately, satisfying this requirement would mean weakening your type checking. That's certainly food for thought, but changing `WeaklyIncrementable` would have ripple effects throughout the iterator concept hierarchy.

Twiddling with difference type is something I've contemplated for a long time. The fact that difference type must be a built-in integral type prevents truly infinite ranges from satisfying the concepts.

**Comment by CaseyCarter** [comment] 2016-11-22 20:01
Specifying the `difference_type` as `long long` suffices to model `WeaklyIncrementable` or `BidirectionalIncrementable`:
```c++
enum class row_t : long long;

row_t &operator++(row_t &x) { x = static_cast<row_t>(static_cast<long long>(x) + 1); return x; }
row_t operator++(row_t &x, int) { auto tmp = x; ++x; return tmp; }

namespace ranges {
    inline namespace v3 {
        template <>
        struct difference_type<::row_t> {
            using type = long long;
        };
    }
}

std::ostream &operator<<(std::ostream &os, row_t const &x) {
    os << "row_t(" << static_cast<long long>(x) << ')';
    return os;
}

int main() {
    auto rng = ranges::view::iota(row_t(0), row_t(4));
    std::cout << rng << '\n';
    std::cout << ranges::view::reverse(rng) << '\n';
}
```
Things only get messy when we want to satisfy `RandomAccessIncrementable`, which requires `-` to return an `Integral` type.

**Comment by gnzlbg** [comment] 2016-11-22 20:11
FWIW 24.2.1 [iterator.requirements.general] is where the standard says that an iterator’s `difference_type` must be a "signed integer type", which are defined in section 3.9.1 [basic.fundamental]. Since all these types model `RandomAccessIncrementable`, weakening the requirement from "signed integer type" to `RandomAccessIncrementable` could be a backwards compatible change.

If a change in this direction could allow infinite ranges and simplify usage of "user defined integers" I think it would be worth exploring.

**Comment by CaseyCarter** [comment] 2016-11-22 20:31
> Since all these types model `RandomAccessIncrementable`, weakening the requirement from "signed integer type" to `RandomAccessIncrementable` could be a backwards compatible change.

Relaxing requirements is only backwards compatible if no one relies on the stronger guarantees; if you replace `RandomAccessIncrementable` with `Destructible` in this argument, the flaw becomes more apparent ;)

One of the critical features of `Integral` types is that all of their operations take constant time. The complexity statements for the algorithms are *vastly* simplified by the requirement that all iterator operations are O(1). Relaxing the `Integral` requirement on difference types without maintaining that O(1) requirement - which is necessary to support difference types that can represent arbitrary distances in infinite ranges - will require reanalyzing algorithm complexities.

I'm not necessarily opposing such a change, just pointing out that it's not as simple as flipping a switch.

**Comment by LucHermitte** [comment] 2016-11-24 18:08
Thank you all for your comments.

Indeed, I've missed `ints()` requirements. Using `iota()` instead solves partially the issue. However having my row type to only model `WeaklyIncrementable` wasn't enough with my compilers (g++-5 and clang 3.7.0-234879). They complain about: `'begin' and 'end' must return the same type`.  IIRC, `begin()` is a `take_exactly_view<iota_view<...` and `end()` a `iota_view<...`. Hence the error.

However, if I have the row type model a `RandomAccessIncrementable`, it compiles.

The last issue remaining is indeed whether types isomorphic to integral type can be accepted as difference types.

BTW, there is something that I find odd.  If I have two iterators (`b` and `e`) on a iota of a `RandomAccessIncrementable` seconds or row numbers, while the difference between `b` and `e` is indeed a number of iterator steps, the difference between `*b` and `*e` should be a number of seconds (or a number of rows). I'm under the impression that `iota()` expects the two types to be the same.

**Comment by gnzlbg** [comment] 2017-03-16 09:03
I think we should close this, since making "opaque integers" model `RandomAccessIncrementable` solves this issue. 

I've opened issue #591 to discuss relaxing `difference_type` to user-defined `Integer` types that satisfy the complexity guarantees of the `Integer` concept (a much smaller change than adding support for `BigInt`s).

**Comment by LucHermitte** [comment] 2017-03-16 10:16
May be the last pending action would be to document somewhere how `iota()` could be used with _strengthened_ integers? 

And if I understand correctly, issue #591 will take care of situations where the `difference_type` is another type -- like for instance the difference between two `time_point`s being a `time_duration`.

**Comment by gnzlbg** [comment] 2017-03-16 10:50
@LucHermitte the docs could use some work (PRs would be really appreciated), but IIUC `iota` "just works" if your type satisfies its requirements. `WeaklyIncrementable` is enough. Looking at the error you are actually seeing when trying it: 

> 'begin' and 'end' must return the same type.

that does not have anything to do with `iota`. The problem is that you are trying to use a C++17 feature (range-based for-loop with iterators of different types) in a compiler that does not implement it. The workaround for that is to use the `RANGES_FOR` macro instead of range-based for loop. Could you maybe try that again but using `RANGES_FOR` instead? (it's an ugly workaround, but for clang <= 3.9 its either that or old iterator based loops).

> And if I understand correctly, issue #591 will take care of situations where the difference_type is another type -- like for instance the difference between two time_points being a time_duration

Kind of, `difference_type` would still need to be some sort of integer type (e.g. floating point types won't probably be valid difference types), so for the example you mention, it would depend on whether `time_duration` would model this or not.

**Comment by LucHermitte** [comment] 2017-03-16 17:32
> > 'begin' and 'end' must return the same type.
> that does not have anything to do with iota. The problem is that you are trying to use a C++17 feature (range-based for-loop with iterators of different types) in a compiler that does not implement it.

Indeed. My mistake! I've discovered this evolution later and I've been using `ranges::for_each()` since then. 
Thanks.

**Comment by gnzlbg** [comment] 2017-03-17 17:12
@ericniebler we can close this, this issue is now superseded by #591.

**Closed** 2017-03-17 18:35 UTC
