### ISSUE TITLE
No matching constructor for initialization of 'ranges::v3::common_pair<int &, float &>'

### ISSUE THREAD

**Issue by MaikKlein** [ericniebler/range-v3#275] opened 2016-01-14 18:42 UTC
```
  std::vector<int> iv{ 1, 3, 4, 5 };
  std::vector<float> fv{ 1, 3, 4, 5 };
  auto r1 = ranges::view::all(iv);
  auto r2 = ranges::view::all(fv);
  auto r3 = ranges::view::zip(r1, r2);
  auto r4 = ranges::view::zip(r3, ranges::view::closed_ints(0ul, ranges::size(r3)));
  auto r5 = ranges::view::concat(r4, r4);
  for (auto t : r5) {
  }
```

This results in:

```
/usr/bin/../lib64/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../../include/c++/5.3.0/bits/stl_pair.h:109:9: error: no matching constructor for initialization of 'ranges::v3::common_pair<int &, float &>'
      : first(), second() { }
        ^
../dependencies/range-v3/include/range/v3/utility/concepts.hpp:611:34: note: in instantiation of member function 'std::pair<ranges::v3::common_pair<int &, float &>, unsigned long>::pair' requested here
                        new T[n]{}
                                 ^
../dependencies/range-v3/include/range/v3/utility/concepts.hpp:115:72: note: while substituting explicitly-specified template arguments into function template 'requires_' 
                typename = decltype(std::declval<Concept &>().template requires_<Ts...>(std::declval<Ts>()...))>
                                                                       ^
../dependencies/range-v3/include/range/v3/utility/concepts.hpp:116:18: note: in instantiation of default argument for 'models_<std::pair<ranges::v3::common_pair<int &, float &>, unsigned long> , ranges::v3::concepts::DefaultConstructible>' required here
            auto models_(Concept *) ->
                 ^~~~~~~~~~~~~~~~~~~~~
../dependencies/range-v3/include/range/v3/utility/concepts.hpp:214:38: note: while substituting deduced template arguments into function template 'models_' [with Ts = (no value), Concept = ranges::v3::concepts::DefaultConstructible, $2 = (no value)]
              : meta::bool_<decltype(detail::models_<Ts...>(_nullptr_v<Concept>()))::type::value>
                                     ^
../dependencies/range-v3/include/range/v3/utility/variant.hpp:142:34: note: in instantiation of template class 'ranges::v3::concepts::models<ranges::v3::concepts::DefaultConstructible, std::pair<ranges::v3::common_pair<int &, float &>, unsigned long> >' requested here
                CONCEPT_REQUIRES(DefaultConstructible<T>())
                                 ^
../dependencies/range-v3/include/range/v3/utility/concepts.hpp:878:70: note: expanded from macro 'CONCEPT_REQUIRES'
            (CONCEPT_PP_CAT(_concept_requires_, __LINE__) == 43) || (__VA_ARGS__),  \
                                                                     ^
/usr/bin/../lib64/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../../include/c++/5.3.0/type_traits:1378:10: note: (skipping 25 contexts in backtrace; use -ftemplate-backtrace-limit=0 to see all)
                              __has_trivial_destructor(_Tp)>>::type
                              ^
../dependencies/range-v3/include/meta/meta.hpp:740:9: note: in instantiation of template type alias '_t' requested here
        using apply_list = _t<extension::apply_list<C, List>>;
        ^
../dependencies/range-v3/include/range/v3/utility/variant.hpp:559:23: note: in instantiation of template type alias 'apply_list' requested here
                meta::apply_list<meta::quote<variant_data>, meta::as_list<Variant>>>::value>
                      ^
../dependencies/range-v3/include/range/v3/utility/variant.hpp:577:29: note: in instantiation of default argument for 'variant_base<ranges::v3::variant<std::pair<ranges::v3::common_pair<int &, float &>, unsigned long>, std::pair<ranges::v3::common_pair<int &, float &>, unsigned long> > >' required here
          : private detail::variant_base<variant<Ts...>>
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
../dependencies/range-v3/include/range/v3/view/concat.hpp:233:63: note: in instantiation of template class 'ranges::v3::variant<std::pair<ranges::v3::common_pair<int &, float &>, unsigned long>, std::pair<ranges::v3::common_pair<int &, float &>, unsigned long> >' requested here
                    return ranges::get<0>(unique_variant(its_.visit(detail::deref_fun<reference>{})));
                                                              ^
../dependencies/range-v3/include/range/v3/range_access.hpp:210:21: note: in instantiation of member function 'ranges::v3::concat_view<ranges::v3::zip_view<ranges::v3::zip_view<ranges::v3::iterator_range<__gnu_cxx::__normal_iterator<int *, std::vector<int, std::allocator<int> > >, __gnu_cxx::__normal_iterator<int *, std::vector<int, std::allocator<int> > > >, ranges::v3::iterator_range<__gnu_cxx::__normal_iterator<float *, std::vector<float, std::allocator<float> > >, __gnu_cxx::__normal_iterator<float *, std::vector<float, std::allocator<float> > > > >, ranges::v3::detail::take_exactly_view_<ranges::v3::iota_view<unsigned long, void>, true> >, ranges::v3::zip_view<ranges::v3::zip_view<ranges::v3::iterator_range<__gnu_cxx::__normal_iterator<int *, std::vector<int, std::allocator<int> > >, __gnu_cxx::__normal_iterator<int *, std::vector<int, std::allocator<int> > > >, ranges::v3::iterator_range<__gnu_cxx::__normal_iterator<float *, std::vector<float, std::allocator<float> > >, __gnu_cxx::__normal_iterator<float *, std::vector<float, std::allocator<float> > > > >, ranges::v3::detail::take_exactly_view_<ranges::v3::iota_view<unsigned long, void>, true> > >::cursor<true>::get' requested here
                pos.get()
                    ^
../dependencies/range-v3/include/range/v3/detail/config.hpp:43:15: note: expanded from macro 'RANGES_DECLTYPE_AUTO_RETURN_NOEXCEPT'
    { return (__VA_ARGS__); }                                   \
              ^
../dependencies/range-v3/include/range/v3/utility/common_tuple.hpp:209:13: note: candidate template ignored: disabled by 'enable_if' [with _concept_requires_209 = 42]
            CONCEPT_REQUIRES(DefaultConstructible<F>() && DefaultConstructible<S>())
            ^
../dependencies/range-v3/include/range/v3/utility/concepts.hpp:878:13: note: expanded from macro 'CONCEPT_REQUIRES'
            (CONCEPT_PP_CAT(_concept_requires_, __LINE__) == 43) || (__VA_ARGS__),  \
            ^
../dependencies/range-v3/include/range/v3/utility/common_tuple.hpp:217:13: note: candidate constructor template not viable: requires 2 arguments, but 0 were provided
            common_pair(F2 &&f2, S2 &&s2)
            ^
../dependencies/range-v3/include/range/v3/utility/common_tuple.hpp:224:13: note: candidate constructor template not viable: requires single argument 'that', but no arguments were provided
            common_pair(std::pair<F2, S2> &that)
            ^
../dependencies/range-v3/include/range/v3/utility/common_tuple.hpp:231:13: note: candidate constructor template not viable: requires single argument 'that', but no arguments were provided
            common_pair(std::pair<F2, S2> const &that)
            ^
../dependencies/range-v3/include/range/v3/utility/common_tuple.hpp:238:13: note: candidate constructor template not viable: requires single argument 'that', but no arguments were provided
            common_pair(std::pair<F2, S2> &&that)
            ^
../dependencies/range-v3/include/range/v3/utility/common_tuple.hpp:199:16: note: candidate constructor (the implicit move constructor) not viable: requires 1 argument, but 0 were provided
        struct common_pair
               ^
../dependencies/range-v3/include/range/v3/utility/common_tuple.hpp:199:16: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 0 were provided
1 error generated.
ninja: build stopped: subcommand failed.
```

I am on master.

**Comment by CaseyCarter** [comment] 2016-01-15 22:13
I can't reproduce this with gcc 5.3 on Ubuntu, the program compiles and runs correctly. Could you try compiling:
```c++
 int iv[] = { 1, 3, 4, 5 };
  float fv[] = { 1, 3, 4, 5 };
  auto r3 = ranges::view::zip(iv, fv);
  auto r4 = ranges::view::zip(r3, ranges::view::closed_ints(0ul, ranges::size(r3)));
  auto r5 = ranges::view::concat(r4, r4);
  for (auto t : r5) {}
```
with -ftemplate-backtrace-limit=0 in the command line, and post the resulting error?

**Comment by MaikKlein** [comment] 2016-01-16 00:01
```
/usr/bin/../lib64/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../../include/c++/5.3.0/bits/stl_pair.h:109:9: error: no matching constructor for initialization of 'ranges::v3::common_pair<int &, float &>'
      : first(), second() { }
        ^
../dependencies/range-v3/include/range/v3/utility/concepts.hpp:611:34: note: in instantiation of member function 'std::pair<ranges::v3::common_pair<int &, float &>, unsigned long>::pair' requested here
                        new T[n]{}
                                 ^
../dependencies/range-v3/include/range/v3/utility/concepts.hpp:115:72: note: while substituting explicitly-specified template arguments into function template 'requires_' 
                typename = decltype(std::declval<Concept &>().template requires_<Ts...>(std::declval<Ts>()...))>
                                                                       ^
../dependencies/range-v3/include/range/v3/utility/concepts.hpp:116:18: note: in instantiation of default argument for 'models_<std::pair<ranges::v3::common_pair<int &, float &>, unsigned long> , ranges::v3::concepts::DefaultConstructible>' required here
            auto models_(Concept *) ->
                 ^~~~~~~~~~~~~~~~~~~~~
../dependencies/range-v3/include/range/v3/utility/concepts.hpp:214:38: note: while substituting deduced template arguments into function template 'models_' [with Ts = (no value), Concept = ranges::v3::concepts::DefaultConstructible, $2 = (no value)]
              : meta::bool_<decltype(detail::models_<Ts...>(_nullptr_v<Concept>()))::type::value>
                                     ^
../dependencies/range-v3/include/range/v3/utility/variant.hpp:142:34: note: in instantiation of template class 'ranges::v3::concepts::models<ranges::v3::concepts::DefaultConstructible, std::pair<ranges::v3::common_pair<int &, float &>, unsigned long> >' requested here
                CONCEPT_REQUIRES(DefaultConstructible<T>())
                                 ^
../dependencies/range-v3/include/range/v3/utility/concepts.hpp:878:70: note: expanded from macro 'CONCEPT_REQUIRES'
            (CONCEPT_PP_CAT(_concept_requires_, __LINE__) == 43) || (__VA_ARGS__),  \
                                                                     ^
/usr/bin/../lib64/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../../include/c++/5.3.0/type_traits:1378:10: note: in instantiation of template class 'ranges::v3::detail::indexed_datum<std::pair<ranges::v3::common_pair<int &, float &>, unsigned long>, std::integral_constant<unsigned long, 0> >' requested here
                              __has_trivial_destructor(_Tp)>>::type
                              ^
../dependencies/range-v3/include/meta/meta.hpp:894:25: note: in instantiation of template class 'std::is_trivially_destructible<ranges::v3::detail::indexed_datum<std::pair<ranges::v3::common_pair<int &, float &>, unsigned long>, std::integral_constant<unsigned long, 0> > >' requested here
                : if_c<!Bool::type::value, std::false_type, _and_<Bools...>>
                        ^
../dependencies/range-v3/include/meta/meta.hpp:147:9: note: in instantiation of template class 'meta::v1::detail::_and_<std::is_trivially_destructible<ranges::v3::detail::indexed_datum<std::pair<ranges::v3::common_pair<int &, float &>, unsigned long>, std::integral_constant<unsigned long, 0> > >, std::is_trivially_destructible<ranges::v3::detail::indexed_datum<std::pair<ranges::v3::common_pair<int &, float &>, unsigned long>, std::integral_constant<unsigned long, 1> > > >' requested here
        using _t = typename T::type;
        ^
../dependencies/range-v3/include/meta/meta.hpp:947:9: note: in instantiation of template type alias '_t' requested here
        using and_ = _t<detail::_and_<Bools...>>;
        ^
../dependencies/range-v3/include/meta/meta.hpp:469:49: note: in instantiation of template type alias 'and_' requested here
            struct defer_<C, list<Ts...>, void_<C<Ts...>>>
                                                ^
../dependencies/range-v3/include/meta/meta.hpp:510:24: note: during template argument deduction for class template partial specialization 'defer_<C, list<type-parameter-0-1...>, typename impl<<type-parameter-0-1...> >::type>' [with C = and_, Ts = <std::is_trivially_destructible<ranges::v3::detail::indexed_datum<std::pair<ranges::v3::common_pair<int &, float &>, unsigned long>, std::integral_constant<unsigned long, 0> > >, std::is_trivially_destructible<ranges::v3::detail::indexed_datum<std::pair<ranges::v3::common_pair<int &, float &>, unsigned long>, std::integral_constant<unsigned long, 1> > >>]
        struct defer : detail::defer_<C, list<Ts...>>
                       ^
../dependencies/range-v3/include/meta/meta.hpp:147:9: note: in instantiation of template class 'meta::v1::defer<and_, std::is_trivially_destructible<ranges::v3::detail::indexed_datum<std::pair<ranges::v3::common_pair<int &, float &>, unsigned long>, std::integral_constant<unsigned long, 0> > >, std::is_trivially_destructible<ranges::v3::detail::indexed_datum<std::pair<ranges::v3::common_pair<int &, float &>, unsigned long>, std::integral_constant<unsigned long, 1> > > >' requested here
        using _t = typename T::type;
        ^
../dependencies/range-v3/include/meta/meta.hpp:650:13: note: in instantiation of template type alias '_t' requested here
            using apply = _t<defer<C, Ts...>>;
            ^
../dependencies/range-v3/include/meta/meta.hpp:404:9: note: in instantiation of template type alias 'apply' requested here
        using apply = typename F::template apply<Args...>;
        ^
../dependencies/range-v3/include/meta/meta.hpp:469:49: note: in instantiation of template type alias 'apply' requested here
            struct defer_<C, list<Ts...>, void_<C<Ts...>>>
                                                ^
../dependencies/range-v3/include/meta/meta.hpp:510:24: note: during template argument deduction for class template partial specialization 'defer_<C, list<type-parameter-0-1...>, typename impl<<type-parameter-0-1...> >::type>' [with C = apply, Ts = <meta::v1::quote<meta::and_>, std::is_trivially_destructible<ranges::v3::detail::indexed_datum<std::pair<ranges::v3::common_pair<int &, float &>, unsigned long>, std::integral_constant<unsigned long, 0> > >, std::is_trivially_destructible<ranges::v3::detail::indexed_datum<std::pair<ranges::v3::common_pair<int &, float &>, unsigned long>, std::integral_constant<unsigned long, 1> > >>]
        struct defer : detail::defer_<C, list<Ts...>>
                       ^
../dependencies/range-v3/include/meta/meta.hpp:725:46: note: in instantiation of template class 'meta::v1::defer<apply, meta::v1::quote<meta::and_>, std::is_trivially_destructible<ranges::v3::detail::indexed_datum<std::pair<ranges::v3::common_pair<int &, float &>, unsigned long>, std::integral_constant<unsigned long, 0> > >, std::is_trivially_destructible<ranges::v3::detail::indexed_datum<std::pair<ranges::v3::common_pair<int &, float &>, unsigned long>, std::integral_constant<unsigned long, 1> > > >' requested here
            struct apply_list<F, T<Ts...>> : lazy::apply<F, Ts...>
                                             ^
../dependencies/range-v3/include/meta/meta.hpp:147:9: note: in instantiation of template class 'meta::v1::extension::apply_list<meta::v1::quote<meta::and_>, meta::v1::list<std::is_trivially_destructible<ranges::v3::detail::indexed_datum<std::pair<ranges::v3::common_pair<int &, float &>, unsigned long>, std::integral_constant<unsigned long, 0> > >, std::is_trivially_destructible<ranges::v3::detail::indexed_datum<std::pair<ranges::v3::common_pair<int &, float &>, unsigned long>, std::integral_constant<unsigned long, 1> > > > >' requested here
        using _t = typename T::type;
        ^
../dependencies/range-v3/include/meta/meta.hpp:740:9: note: in instantiation of template type alias '_t' requested here
        using apply_list = _t<extension::apply_list<C, List>>;
        ^
../dependencies/range-v3/include/range/v3/utility/variant.hpp:292:23: note: in instantiation of template type alias 'apply_list' requested here
                meta::apply_list<
                      ^
../dependencies/range-v3/include/range/v3/utility/variant.hpp:352:13: note: in instantiation of default argument for 'variant_data_<meta::v1::list<ranges::v3::detail::indexed_datum<std::pair<ranges::v3::common_pair<int &, float &>, unsigned long>, std::integral_constant<unsigned long, 0> >, ranges::v3::detail::indexed_datum<std::pair<ranges::v3::common_pair<int &, float &>, unsigned long>, std::integral_constant<unsigned long, 1> > > >' required here
            using variant_data =
            ^~~~~
../dependencies/range-v3/include/meta/meta.hpp:469:49: note: in instantiation of template type alias 'variant_data' requested here
            struct defer_<C, list<Ts...>, void_<C<Ts...>>>
                                                ^
../dependencies/range-v3/include/meta/meta.hpp:510:24: note: during template argument deduction for class template partial specialization 'defer_<C, list<type-parameter-0-1...>, typename impl<<type-parameter-0-1...> >::type>' [with C = variant_data, Ts = <std::pair<ranges::v3::common_pair<int &, float &>, unsigned long>, std::pair<ranges::v3::common_pair<int &, float &>, unsigned long>>]
        struct defer : detail::defer_<C, list<Ts...>>
                       ^
../dependencies/range-v3/include/meta/meta.hpp:147:9: note: in instantiation of template class 'meta::v1::defer<variant_data, std::pair<ranges::v3::common_pair<int &, float &>, unsigned long>, std::pair<ranges::v3::common_pair<int &, float &>, unsigned long> >' requested here
        using _t = typename T::type;
        ^
../dependencies/range-v3/include/meta/meta.hpp:650:13: note: in instantiation of template type alias '_t' requested here
            using apply = _t<defer<C, Ts...>>;
            ^
../dependencies/range-v3/include/meta/meta.hpp:404:9: note: in instantiation of template type alias 'apply' requested here
        using apply = typename F::template apply<Args...>;
        ^
../dependencies/range-v3/include/meta/meta.hpp:469:49: note: in instantiation of template type alias 'apply' requested here
            struct defer_<C, list<Ts...>, void_<C<Ts...>>>
                                                ^
../dependencies/range-v3/include/meta/meta.hpp:510:24: note: during template argument deduction for class template partial specialization 'defer_<C, list<type-parameter-0-1...>, typename impl<<type-parameter-0-1...> >::type>' [with C = apply, Ts = <meta::v1::quote<variant_data>, std::pair<ranges::v3::common_pair<int &, float &>, unsigned long>, std::pair<ranges::v3::common_pair<int &, float &>, unsigned long>>]
        struct defer : detail::defer_<C, list<Ts...>>
                       ^
../dependencies/range-v3/include/meta/meta.hpp:725:46: note: in instantiation of template class 'meta::v1::defer<apply, meta::v1::quote<variant_data>, std::pair<ranges::v3::common_pair<int &, float &>, unsigned long>, std::pair<ranges::v3::common_pair<int &, float &>, unsigned long> >' requested here
            struct apply_list<F, T<Ts...>> : lazy::apply<F, Ts...>
                                             ^
../dependencies/range-v3/include/meta/meta.hpp:147:9: note: in instantiation of template class 'meta::v1::extension::apply_list<meta::v1::quote<variant_data>, meta::v1::list<std::pair<ranges::v3::common_pair<int &, float &>, unsigned long>, std::pair<ranges::v3::common_pair<int &, float &>, unsigned long> > >' requested here
        using _t = typename T::type;
        ^
../dependencies/range-v3/include/meta/meta.hpp:740:9: note: in instantiation of template type alias '_t' requested here
        using apply_list = _t<extension::apply_list<C, List>>;
        ^
../dependencies/range-v3/include/range/v3/utility/variant.hpp:559:23: note: in instantiation of template type alias 'apply_list' requested here
                meta::apply_list<meta::quote<variant_data>, meta::as_list<Variant>>>::value>
                      ^
../dependencies/range-v3/include/range/v3/utility/variant.hpp:577:29: note: in instantiation of default argument for 'variant_base<ranges::v3::variant<std::pair<ranges::v3::common_pair<int &, float &>, unsigned long>, std::pair<ranges::v3::common_pair<int &, float &>, unsigned long> > >' required here
          : private detail::variant_base<variant<Ts...>>
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
../dependencies/range-v3/include/range/v3/view/concat.hpp:233:63: note: in instantiation of template class 'ranges::v3::variant<std::pair<ranges::v3::common_pair<int &, float &>, unsigned long>, std::pair<ranges::v3::common_pair<int &, float &>, unsigned long> >' requested here
                    return ranges::get<0>(unique_variant(its_.visit(detail::deref_fun<reference>{})));
                                                              ^
../dependencies/range-v3/include/range/v3/range_access.hpp:210:21: note: in instantiation of member function 'ranges::v3::concat_view<ranges::v3::zip_view<ranges::v3::zip_view<ranges::v3::iterator_range<int *, int *>, ranges::v3::iterator_range<float *, float *> >, ranges::v3::detail::take_exactly_view_<ranges::v3::iota_view<unsigned long, void>, true> >, ranges::v3::zip_view<ranges::v3::zip_view<ranges::v3::iterator_range<int *, int *>, ranges::v3::iterator_range<float *, float *> >, ranges::v3::detail::take_exactly_view_<ranges::v3::iota_view<unsigned long, void>, true> > >::cursor<true>::get' requested here
                pos.get()
                    ^
                pos.get()
                    ^
../dependencies/range-v3/include/range/v3/detail/config.hpp:43:15: note: expanded from macro 'RANGES_DECLTYPE_AUTO_RETURN_NOEXCEPT'
    { return (__VA_ARGS__); }                                   \
              ^
../dependencies/range-v3/include/range/v3/utility/common_tuple.hpp:209:13: note: candidate template ignored: disabled by 'enable_if' [with _concept_requires_209 = 42]
            CONCEPT_REQUIRES(DefaultConstructible<F>() && DefaultConstructible<S>())
            ^
../dependencies/range-v3/include/range/v3/utility/concepts.hpp:878:13: note: expanded from macro 'CONCEPT_REQUIRES'
            (CONCEPT_PP_CAT(_concept_requires_, __LINE__) == 43) || (__VA_ARGS__),  \
            ^
../dependencies/range-v3/include/range/v3/utility/common_tuple.hpp:217:13: note: candidate constructor template not viable: requires 2 arguments, but 0 were provided
            common_pair(F2 &&f2, S2 &&s2)
            ^
../dependencies/range-v3/include/range/v3/utility/common_tuple.hpp:224:13: note: candidate constructor template not viable: requires single argument 'that', but no arguments were provided
            common_pair(std::pair<F2, S2> &that)
            ^
../dependencies/range-v3/include/range/v3/utility/common_tuple.hpp:231:13: note: candidate constructor template not viable: requires single argument 'that', but no arguments were provided
            common_pair(std::pair<F2, S2> const &that)
            ^
../dependencies/range-v3/include/range/v3/utility/common_tuple.hpp:238:13: note: candidate constructor template not viable: requires single argument 'that', but no arguments were provided
            common_pair(std::pair<F2, S2> &&that)
            ^
../dependencies/range-v3/include/range/v3/utility/common_tuple.hpp:199:16: note: candidate constructor (the implicit move constructor) not viable: requires 1 argument, but 0 were provided
        struct common_pair
               ^
../dependencies/range-v3/include/range/v3/utility/common_tuple.hpp:199:16: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 0 were provided
1 error generated.
```

**Comment by CaseyCarter** [comment] 2016-01-17 18:35
The error occurs when instantiating `ranges::detail::indexed_datum<std::pair<ranges::common_pair<int &, float &>, unsigned long>, std::integral_constant<unsigned long, 0> >`.

After an hour of tracing the headers trying to figure out what's going on here, I noticed that the content of the diagnostic messages doesn't look like the output of g++. Those are in fact clang diagnostics. The error is easily reproducible compiling the example program with clang using libstdc++. Minimal test case:

```c++
#include <range/v3/utility/concepts.hpp>

// a la ranges::common_pair and ranges::detail::indexed_datum
template <class T>
struct constrained {
  T t_;

  CONCEPT_REQUIRES(ranges::DefaultConstructible<T>())
  constrained() : t_() {}
};

// a la libstdc++ std::pair
template <class T>
struct unconstrained {
  T t_;

  constexpr unconstrained() : t_() {}
};

int main() {
  static_assert(!ranges::DefaultConstructible<
    constrained<unconstrained<constrained<int&>>>>(), "");
}
```
The error does not occur if either:
* the default constructor of `unconstrained` is constrained with `CONCEPT_REQUIRES(DefaultConstuctible<T>())`
* the default constructor of `unconstrained` is not marked `constexpr`

The example program in the OP compiles correctly if either:
* GCC is used to compile the program. GCC is less aggressive about instantiating `constexpr` functions and diagnosing occurrences of ill-formed NDR behavior therein. Compiling with GCC actually causes the `static_assert` to fire in the minimal test case: it believes the subject type *is* default constructible.
* libc++ is used as the standard library when compiling with clang. The default constructor of libc++'s `std::pair<T, U>` implementation is constrained with `is_default_constructible<T>() && is_default_constructible<U>()`.

I am reasonably certain that both the program in the OP and the test case are ill-formed NDR with the libstdc++ implementation of `pair`, so that both GCC and clang are conforming despite differing in their behavior. I think the best thing for rv3 would be to use `common_pair` and `common_tuple` everywhere - possibly renaming them to `pair` and `tuple` - and avoid `std::pair` and `std::tuple` wherever possible.

**Comment by ericniebler** [comment] 2016-01-17 23:07
If libstdc++'s  `pair` and `tuple` default constructors are unconstrained, then they haven't implemented the proposed resolution for https://cplusplus.github.io/LWG/lwg-defects.html#2367. The current Working Draft is clear: the default constructors should be constrained.

**Comment by CaseyCarter** [comment] 2016-01-17 23:30
Oh, cool beans. I should have checked the wp instead of n4140. I'll file an issue with gcc to be sure the resolution of 2367 is in 5.4 and we can close this.

**Comment by CaseyCarter** [comment] 2016-01-19 19:35
Filed [GCC PR 69365](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=69365). I don't have high hopes for the fix being backported from trunk to the gcc-5-branch since the bug is not a regression; clang + libstdc++ may not be functional until GCC6 release.

**Comment by CaseyCarter** [comment] 2016-01-19 19:56
I suppose I should mention that in the meantime the problem can be corrected by applying this patch to libstdc++'s bits/stl_pair.h:

```
--- /usr/include/c++/5.3.0/bits/stl_pair.h	2016-01-19 13:26:18.572082636 -0600
+++ stl_pair.h	2016-01-19 13:26:12.180082636 -0600
@@ -105,6 +105,11 @@
       // 265.  std::pair::pair() effects overly restrictive
       /** The default constructor creates @c first and @c second using their
        *  respective default constructors.  */
+#if __cplusplus >= 201103L
+      template<class _U1 = _T1, class _U2 = _T2, class = typename
+               enable_if<__and_<is_default_constructible<_U1>,
+                                is_default_constructible<_U2>>::value>::type>
+#endif
       _GLIBCXX_CONSTEXPR pair()
       : first(), second() { }
 
```

**Comment by CaseyCarter** [comment] 2018-05-02 13:00
> Filed [GCC PR 69365](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=69365). I don't have high hopes for the fix being backported from trunk to the gcc-5-branch since the bug is not a regression; clang + libstdc++ may not be functional until GCC6 release.

The PR has been WONTFIXed: GCC5 has been closed for a while now. I don't think this is something we can feasibly workaround, we'd have to avoid `std::pair` completely. Clang + libstdc++ 5 is unsupportable, we should redirect people who hit this problem to libc++ or a more recent libstdc++.

**Closed by CaseyCarter** 2018-05-02 13:00 UTC

**Comment by gnzlbg** [comment] 2018-05-02 14:11
@CaseyCarter is there a way to `#pragma error "..."` or `#pragma warning "..."` here?

**Comment by CaseyCarter** [comment] 2018-05-02 14:27
AFAIK libstdc++ still has no useful versioning information that would enable us to do something at the preprocessor level.

**Comment by gnzlbg** [comment] 2018-05-02 14:59
Oh well, nvm then.
